Repository home-assistant/android, pull requests merged in 2019-12, with the labels that each got.

#74 Device Tracking
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/background/ReceiverComponent.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationException.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRequest.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationService.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/UpdateLocationRequest.kt
  data/src/test/java/io/homeassistant/companion/android/data/HomeAssistantMockService.kt
  data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
  data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationServiceSpec.kt
  data/src/test/resources/integration/empty.json
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/UpdateLocation.kt
  domain/src/test/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImplSpec.kt
Labels: cla-signed

#72 Add Lokalise SDK
  app/build.gradle
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl-rNL/strings.xml
  app/src/main/res/values-pl-rPL/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: cla-signed

#87 [Lokalize] Update version
  app/build.gradle
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed

#88 [TRAVIS] Release version name
  .travis/script.sh
  app/build.gradle
Labels: cla-signed

#93 Fix double application registration.
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
Labels: cla-signed

#109 fix #102
  app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupFragment.kt
  app/src/main/res/layout/fragment_manual_setup.xml
Labels: cla-signed

#116 Fix vertical accuracy.
  app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/UpdateLocationRequest.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/UpdateLocation.kt
Labels: cla-signed

#120 Remove Lokalise SDK
  app/build.gradle
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed

#129 Feature/location settings
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/PresenterComponent.kt
  app/src/main/java/io/homeassistant/companion/android/PresenterModule.kt
  app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsView.kt
  app/src/main/java/io/homeassistant/companion/android/util/PermissionManager.kt
  app/src/main/res/drawable/map_marker.xml
  app/src/main/res/drawable/map_marker_radius.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-nl-rNL/strings.xml
  app/src/main/res/values-pl-rPL/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/preferences.xml
  common/src/main/java/io/homeassistant/companion/android/common/LocalStorageImpl.kt
  data/src/main/java/io/homeassistant/companion/android/data/LocalStorage.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/EntityResponse.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRequest.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationService.kt
  data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/Entity.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/ZoneAttributes.kt
  domain/src/test/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImplSpec.kt
Labels: cla-signed

#142 Add some error handling around getting zones from HA.
  app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
Labels: cla-signed

#135 Location permission fixes
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/util/PermissionManager.kt
Labels: cla-error, cla-signed

#140 Basic Notification Support
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/ServiceComponent.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
  app/src/test/java/io/homeassistant/companion/android/launch/LaunchPresenterImplSpec.kt
  app/src/test/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImplSpec.kt
  build.gradle
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationService.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/RegisterDeviceRequest.kt
  data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/DeviceRegistration.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
  domain/src/test/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImplSpec.kt
Labels: cla-signed

#152 Bugfix/disable location tracking
  app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
Labels: cla-signed

#155 Fix dialog button color in webview.
  app/src/main/res/layout/fragment_manual_setup.xml
  app/src/main/res/values/styles.xml
Labels: cla-signed

#156 Url improvement
  app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupPresenterImpl.kt
  app/src/test/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupPresenterImplSpec.kt
  data/src/main/java/io/homeassistant/companion/android/data/authentication/AuthenticationRepositoryImpl.kt
  data/src/test/java/io/homeassistant/companion/android/data/authentication/AuthenticationRepositoryImplSpec.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/MalformedHttpUrlException.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/authentication/AuthenticationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/authentication/AuthenticationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/authentication/AuthenticationUseCaseImpl.kt
  domain/src/test/java/io/homeassistant/companion/android/domain/authentication/AuthenticationUseCaseImplSpec.kt
Labels: cla-signed

#157 Application style
  app/src/main/res/layout/fragment_discovery.xml
  app/src/main/res/layout/fragment_manual_setup.xml
  app/src/main/res/layout/fragment_mobile_app_integration.xml
  app/src/main/res/values/styles.xml
Labels: cla-signed

#161 Add back Lokalise SDK
  app/build.gradle
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed

#160 WebView rotation
  app/src/main/AndroidManifest.xml
Labels: cla-signed

#169 Small typo
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: cla-signed

#175 Lokalise: Translations update
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nl-rNL/strings.xml
  app/src/main/res/values-pl-rPL/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values/strings.xml
Labels: cla-error

#163 Fix some styling
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/fragment_manual_setup.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: cla-signed

#158 Allow editing of Device Name
  app/build.gradle
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
  app/src/test/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImplSpec.kt
  build.gradle
  common/src/main/java/io/homeassistant/companion/android/common/dagger/DataModule.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/DeviceRegistration.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
  domain/src/test/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImplSpec.kt
Labels: cla-signed

#178 [CI] Change log
  .travis/script.sh
Labels: cla-signed

#179 [CI] Version Code
  .travis.yml
Labels: cla-signed

#180 Only send the needed data on update registration.
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
Labels: cla-signed

#183 Add Lokalise info to readme.
  README.md
Labels: cla-signed

#182 Fix Dead end when entering invalid Home Assistant url during onboarding #105
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt
  app/src/main/res/values/strings.xml
Labels: cla-signed

#188 Make sure mobile_app is required.
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationListener.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
  app/src/main/res/layout/fragment_mobile_app_integration.xml
  app/src/test/java/io/homeassistant/companion/android/launch/LaunchPresenterImplSpec.kt
  app/src/test/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImplSpec.kt
Labels: cla-signed

#181 Set minimum accuracy for location updates.
  app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
Labels: cla-signed

#194 Allow user certs imported into android to be accepted.
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/network_security_config.xml
Labels: cla-signed

#200 Add link to companion documentation.
  README.md
Labels: cla-signed

#204 Upgrade to kotlin 1.3.60
  build.gradle
Labels: cla-signed

#195 Support remoteUiUrl from the mobile_app integration.
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/test/java/io/homeassistant/companion/android/webview/WebViewPresenterImplSpec.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
  domain/src/test/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImplSpec.kt
Labels: cla-signed
