Repository home-assistant/android, pull requests merged in 2020-07, with the labels that each got.

#643 Fix left empty notifications groups
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/NotificationContentReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/NotificationDeleteReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/util/NotificationActionContentHandler.kt
  app/src/main/java/io/homeassistant/companion/android/util/NotificationManagerExtensions.kt
Labels: cla-signed

#648 Lokalise: Translations update
  app/src/main/res/values-cy-rGB/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl-rPL/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: cla-signed

#649 Bump Version for 1.10.0 Release
  buildSrc/src/main/kotlin/Config.kt
Labels: cla-signed

#625 Fix Biometric Unlock & Enhancement
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/PresenterComponent.kt
  app/src/main/java/io/homeassistant/companion/android/PresenterModule.kt
  app/src/main/java/io/homeassistant/companion/android/authenticator/Authenticator.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchView.kt
  app/src/main/java/io/homeassistant/companion/android/lock/LockActivity.kt
  app/src/main/java/io/homeassistant/companion/android/lock/LockPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/lock/LockPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/lock/LockView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/main/res/drawable/ic_timeout.xml
  app/src/main/res/drawable/lock_icon.png
  app/src/main/res/layout/activity_lock.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/activity_webview.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
  app/src/test/java/io/homeassistant/companion/android/launch/LaunchPresenterImplSpec.kt
  buildSrc/src/main/kotlin/Config.kt
  common/src/main/java/io/homeassistant/companion/android/common/LocalStorageImpl.kt
  data/src/main/java/io/homeassistant/companion/android/data/LocalStorage.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
Labels: cla-signed

#651 Hot fix removing authentication from settings.
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/res/layout/activity_settings.xml
Labels: cla-signed

#652 First attempt at CI action
  .github/mock-google-services.json
  .github/workflows/beta.yml
  .github/workflows/pr.yml
  .travis.yml
  .travis/before_install.sh
  .travis/script.sh
  .travis/secrets.tar.enc
  README.md
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Config.kt
Labels: cla-signed

#657 Lokalise: Translations update
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-cy-rGB/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl-rNL/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl-rPL/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  app/src/main/res/values/strings.xml
Labels: cla-signed

#633 Authentication Dialog Enhancement
  app/build.gradle.kts
  app/src/main/java/io/homeassistant/companion/android/database/AppDataBase.kt
  app/src/main/java/io/homeassistant/companion/android/database/AuthenticationDataBaseDao.kt
  app/src/main/java/io/homeassistant/companion/android/database/AuthenticationList.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/res/drawable/ic_visibility.xml
  app/src/main/res/drawable/ic_visibility_off.xml
  app/src/main/res/layout/dialog_authentication.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  buildSrc/src/main/kotlin/Config.kt
Labels: cla-signed, enhancement, minor

#650 Fix widget service calls with numbers (#640)
  app/build.gradle.kts
  app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidgetConfigureActivity.kt
Labels: bug, cla-signed, patch

#664 Ensure thread safety around NsdManager.
  app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantSearcher.kt
Labels: cla-signed, patch

#662 Ensure sensors only start when we are actually logged in.
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed, patch

#663 Only update registration when we are actually connected to HA.
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Labels: cla-signed, patch

#668 Fix translation.
  app/src/main/res/values/strings.xml
Labels: bug, cla-signed, patch

#669 Ensure we have permissions before trying to get Wifi data
  app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
Labels: bug, cla-signed, patch

#673 Allow the firebase instance id be optional.
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
  app/src/main/res/layout/fragment_mobile_app_integration.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
Labels: bug, cla-signed, patch

#674 Bugfix/various fixes
  app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantSearcher.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidgetConfigureActivity.kt
  app/src/main/res/values/strings.xml
Labels: bug, cla-signed, patch

#682 Minimal Android Flavor
  .github/mock-google-services.json
  .github/workflows/beta.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  app/build.gradle.kts
  app/src/full/AndroidManifest.xml
  app/src/full/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
  app/src/full/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
  app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
  app/src/full/java/io/homeassistant/companion/android/notifications/NotificationAction.kt
  app/src/full/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
  app/src/full/java/io/homeassistant/companion/android/notifications/NotificationContentReceiver.kt
  app/src/full/java/io/homeassistant/companion/android/notifications/NotificationDeleteReceiver.kt
  app/src/full/java/io/homeassistant/companion/android/notifications/ServiceComponent.kt
  app/src/full/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/AllSensorsUpdaterImpl.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiverBase.kt
  app/src/main/java/io/homeassistant/companion/android/background/ReceiverComponent.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchPresenterBase.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterBase.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/AllSensorsUpdater.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
  app/src/main/java/io/homeassistant/companion/android/util/PermissionManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/minimal/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
  app/src/minimal/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
  app/src/minimal/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/AllSensorsUpdaterImpl.kt
  app/src/test/java/io/homeassistant/companion/android/launch/LaunchPresenterImplSpec.kt
  app/src/test/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImplSpec.kt
  buildSrc/src/main/kotlin/Config.kt
Labels: cla-signed, enhancement, major

#683 Fix Deploy and Release
  .github/workflows/beta.yml
  .github/workflows/release.yml
Labels: cla-signed

#684 Fix Deploy and Release for Real
  .github/workflows/beta.yml
  .github/workflows/release.yml
Labels: cla-signed
