Repository home-assistant/android, pull requests merged in 2020-08, with the labels that each got.

#686 Migrate to Sentry and remove Crashlytics
  app/build.gradle.kts
  app/src/full/AndroidManifest.xml
  build.gradle.kts
  buildSrc/src/main/kotlin/Config.kt
Labels: cla-signed

#691 Fix location tracking
  app/src/full/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
  app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Labels: cla-signed

#695 Ensure the correct class is used for broadcast of location updates.
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: bug, cla-signed, patch

#692 Request accurate location when we update sensors.
  app/src/main/java/io/homeassistant/companion/android/sensors/AllSensorsUpdater.kt
Labels: cla-signed, enhancement, patch

#693 Add device_id whenever we fire an event.
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
Labels: cla-signed, enhancement, patch

#696 Disable Sentry.io for debug builds.
  app/build.gradle.kts
  app/src/full/AndroidManifest.xml
Labels: cla-signed, enhancement, patch

#697 Lokalise: Translations update
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl-rNL/strings.xml
  app/src/main/res/values-pl-rPL/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: cla-signed

#699 Disable minimal publishing.
  app/build.gradle.kts
Labels: bug, cla-signed, patch

#702 Entity State Widget bugfix
  app/src/main/java/io/homeassistant/companion/android/widgets/StaticWidget.kt
Labels: cla-signed

#707 Mention app flavors and actions APK in the read me file
  README.md
Labels: cla-signed

#706 Correct accuracy for location tracking
  app/src/full/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
Labels: cla-signed

#712 Notifications - HTML formatting for title, group summary and collapsed notifications
  app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Labels: bug, cla-signed, patch

#714 Fix statusbar color if theme used rgb color instead of hex color
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
Labels: cla-signed

#716 Fix statusbar not readable when using a light theme (#433)
  app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
Labels: cla-signed

#717 Fix android dark mode
  app/build.gradle.kts
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/res/values-v29/styles.xml
  buildSrc/src/main/kotlin/Config.kt
Labels: cla-signed

#721 Make sure titles for notifications are optional.
  app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Labels: bug, cla-signed, patch

#722 fix: Biomatric authentication skip issue
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: bug, cla-signed, patch

#723 Fix missing message if notification is collapsed
  app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
Labels: cla-signed

#726 Initial commit of next alarm sensor
  app/src/full/java/io/homeassistant/companion/android/sensors/AllSensorsUpdaterImpl.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorComponent.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/AllSensorsUpdaterImpl.kt
Labels: cla-signed, enhancement, minor

#689 WIP: Add nfc support
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/nfc/NFCUtil.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcEditFragment.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcReadFragment.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcWelcomeFragment.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcWriteFragment.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/ProviderComponent.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/SingleLiveEvent.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/TagReaderActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/util/UrlHandler.kt
  app/src/main/res/layout/activity_nfc_setup.xml
  app/src/main/res/layout/activity_tag_reader.xml
  app/src/main/res/layout/content_nfc_setup.xml
  app/src/main/res/layout/fragment_nfc_edit.xml
  app/src/main/res/layout/fragment_nfc_read.xml
  app/src/main/res/layout/fragment_nfc_welcome.xml
  app/src/main/res/layout/fragment_nfc_write.xml
  app/src/main/res/navigation/nfc_nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
  buildSrc/src/main/kotlin/Config.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationService.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
Labels: cla-signed, enhancement, minor

#732 Fix configure widget theme colors
  app/src/main/res/layout/fragment_mobile_app_integration.xml
  app/src/main/res/layout/widget_button_configure.xml
  app/src/main/res/layout/widget_static_configure.xml
Labels: bug, cla-signed, patch

#734 Update wifi sensor on state changes
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorComponent.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/WifiStateReceiver.kt
Labels: cla-signed

#740 Battery and next alarm sensor improvements
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/ChargingBroadcastReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
Labels: bug, cla-signed, patch

#731 Telephony state support
  app/src/full/java/io/homeassistant/companion/android/sensors/AllSensorsUpdaterImpl.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterBase.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/util/PermissionManager.kt
  app/src/main/res/drawable/ic_phone.xml
  app/src/main/res/layout/fragment_mobile_app_integration.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
  app/src/minimal/java/io/homeassistant/companion/android/sensors/AllSensorsUpdaterImpl.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
Labels: cla-signed, enhancement, patch

#742 Sensor Screen
  app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/AllSensorsUpdaterImpl.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/PresenterComponent.kt
  app/src/main/java/io/homeassistant/companion/android/SensorUpdater.kt
  app/src/main/java/io/homeassistant/companion/android/background/LocationBroadcastReceiverBase.kt
  app/src/main/java/io/homeassistant/companion/android/background/ReceiverComponent.kt
  app/src/main/java/io/homeassistant/companion/android/database/AppDataBase.kt
  app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  app/src/main/java/io/homeassistant/companion/android/database/authentication/Authentication.kt
  app/src/main/java/io/homeassistant/companion/android/database/authentication/AuthenticationDao.kt
  app/src/main/java/io/homeassistant/companion/android/database/sensor/Sensor.kt
  app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterBase.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/AllSensorsUpdater.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/ChargingBroadcastReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorComponent.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/WifiStateReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/util/PermissionManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/res/drawable/leak.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/sensor_detail.xml
  app/src/main/res/xml/sensors.xml
  app/src/minimal/java/io/homeassistant/companion/android/background/LocationBroadcastReceiver.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/AllSensorsUpdaterImpl.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/Sensor.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/SensorRegistration.kt
  domain/src/test/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImplSpec.kt
Labels: cla-signed, enhancement, minor

#744 NFC Fixes
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcEditFragment.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
Labels: bug, cla-signed, patch

#743 Add Bluetooth sensor
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorComponent.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/util/PermissionManager.kt
Labels: cla-signed

#746 Remove multiple sensor receivers
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantBootReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorComponent.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/WifiStateReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsView.kt
  app/src/main/java/io/homeassistant/companion/android/util/PermissionManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
Labels: cla-signed, misc, patch

#747 Lokalise: Translations update
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl-rNL/strings.xml
  app/src/main/res/values-pl-rPL/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: cla-signed

#752 Ensure when sensors are disabled they aren't still polling.
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/ChargingBroadcastReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
  app/src/main/res/values/strings.xml
  app/src/minimal/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
Labels: bug, cla-signed, minor

#753 Try to fix some location issues
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
Labels: bug, cla-signed, patch

#750 Add storage sensor
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt
Labels: cla-signed, enhancement, patch

#749 Fix status bar / navigation bar / app colors on dark mode
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidgetConfigureActivity.kt
  app/src/main/res/drawable/ic_flash_on_24dp.xml
  app/src/main/res/drawable/ic_home_24dp.xml
  app/src/main/res/drawable/ic_lightbulb_outline_24dp.xml
  app/src/main/res/drawable/ic_power_settings_new_24dp.xml
  app/src/main/res/drawable/navigate_next.xml
  app/src/main/res/drawable/widget_button_background.xml
  app/src/main/res/layout/activity_nfc_setup.xml
  app/src/main/res/layout/widget_button.xml
  app/src/main/res/layout/widget_image_spinner.xml
  app/src/main/res/layout/widget_static.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-v29/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: bug, cla-signed, patch

#764 Dagger Injection Fixes
  app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt
Labels: bug, cla-signed, patch

#761 Add light sensor
  app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, enhancement, patch

#765 Fix duplicate attributes showing in UI
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
Labels: bug, cla-signed, patch

#766 Fix light sensor crash on older devices that don't have one
  app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
Labels: cla-signed

#770 Attempt to fix SD card path in storage sensor
  app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt
Labels: bug, cla-signed, patch

#776 Allow certain fields to be copied
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
Labels: cla-signed, enhancement, patch

#775 Change order of package for apps that don't provide it
  app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
Labels: bug, cla-signed, patch

#778 Fix issue with Room DB migrations.
  app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
Labels: bug, cla-signed, patch

#741 Add easier way to use of emoji in notifications
  app/build.gradle.kts
  app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
  buildSrc/src/main/kotlin/Config.kt
Labels: cla-signed, enhancement, patch

#745 Let widgets use any material icon
  app/build.gradle.kts
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/ButtonWidget.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/ButtonWidgetDao.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidget.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetDao.kt
  app/src/main/java/io/homeassistant/companion/android/migrations/Migrations.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidgetConfigSpinnerAdaptor.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/StaticWidget.kt
  app/src/main/res/drawable/ic_home_24dp.xml
  app/src/main/res/drawable/ic_lightbulb_outline_24dp.xml
  app/src/main/res/drawable/ic_power_settings_new_24dp.xml
  app/src/main/res/layout/widget_button_configure.xml
  app/src/main/res/layout/widget_image_spinner.xml
  buildSrc/src/main/kotlin/Config.kt
  common/src/main/java/io/homeassistant/companion/android/common/dagger/AppComponent.kt
  common/src/main/java/io/homeassistant/companion/android/common/dagger/DataComponent.kt
  common/src/main/java/io/homeassistant/companion/android/common/dagger/DataModule.kt
  common/src/main/java/io/homeassistant/companion/android/common/dagger/DomainComponent.kt
  common/src/main/java/io/homeassistant/companion/android/common/dagger/DomainModule.kt
  common/src/main/java/io/homeassistant/companion/android/common/dagger/Graph.kt
  common/src/main/java/io/homeassistant/companion/android/common/migrations/Migrations.kt
  data/src/main/java/io/homeassistant/companion/android/data/widgets/WidgetRepositoryImpl.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/widgets/WidgetRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/widgets/WidgetUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/widgets/WidgetUseCaseImpl.kt
  domain/src/test/java/io/homeassistant/companion/android/domain/widgets/WidgetUseCaseImplSpec.kt
Labels: cla-signed, enhancement, patch

#781 Fix name-spacing issue
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/ButtonWidgetDao.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/ButtonWidgetEntity.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetDao.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetEntity.kt
  app/src/main/java/io/homeassistant/companion/android/migrations/Migrations.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/StaticWidget.kt
Labels: bug, cla-signed, patch

#771 Added multiple entity state widget options
  app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetEntity.kt
  app/src/main/java/io/homeassistant/companion/android/migrations/Migrations.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/StaticWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/StaticWidgetConfigureActivity.kt
  app/src/main/res/layout/widget_static_configure.xml
  app/src/main/res/values/strings.xml
Labels: cla-signed, enhancement, patch

#790 Add a template widget
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/TemplateWidgetDao.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/TemplateWidgetEntity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/ProviderComponent.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
  app/src/main/res/layout/widget_template.xml
  app/src/main/res/layout/widget_template_configure.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/template_widget_info.xml
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImpl.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/IntegrationService.kt
  data/src/main/java/io/homeassistant/companion/android/data/integration/entities/Template.kt
  data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationRepositoryImplSpec.kt
  data/src/test/java/io/homeassistant/companion/android/data/integration/IntegrationServiceSpec.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationRepository.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCase.kt
  domain/src/main/java/io/homeassistant/companion/android/domain/integration/IntegrationUseCaseImpl.kt
Labels: cla-signed, enhancement, minor

#792 Add steps counter sensor
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt
Labels: cla-signed, enhancement, patch

#786 Enhance PhoneStateSensorManager with carrier information sensors
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
Labels: cla-signed, enhancement, patch

#794 Add last reboot sensor
  app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, enhancement, patch

#795 Increased connection delay
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: bug, cla-signed, patch

#789 Added possibility to use multiple attributes for static widgets
  app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  app/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetEntity.kt
  app/src/main/java/io/homeassistant/companion/android/migrations/Migrations.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/StaticWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/StaticWidgetConfigureActivity.kt
  app/src/main/res/layout/widget_static_configure.xml
  app/src/main/res/values/strings.xml
Labels: cla-signed, enhancement, patch

#739 Add Exoplayer view and interface
  app/build.gradle.kts
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/res/drawable/ic_baseline_fullscreen_24.xml
  app/src/main/res/drawable/ic_baseline_fullscreen_exit_24.xml
  app/src/main/res/drawable/ic_baseline_volume_off_24.xml
  app/src/main/res/drawable/ic_baseline_volume_up_24.xml
  app/src/main/res/layout/activity_webview.xml
  app/src/main/res/layout/exo_playback_control_view.xml
  buildSrc/src/main/kotlin/Config.kt
Labels: cla-signed, enhancement, patch

#784 Activity recognition sensor added
  app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorComponent.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
Labels: cla-signed, enhancement, patch

#803 Add pressure sensor
  app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, enhancement, patch

#806 Add audio sensor
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, enhancement, patch

#810 Fixed widget errors with service calls containing "entity_id: all"
  app/src/main/java/io/homeassistant/companion/android/widgets/ButtonWidget.kt
  data/src/main/java/io/homeassistant/companion/android/data/HomeAssistantRetrofit.kt
Labels: bug, cla-signed, patch

#801 Add proximity sensor
  app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, enhancement, patch

#809 Sensor Refactor
  app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  app/src/main/java/io/homeassistant/companion/android/database/sensor/Attribute.kt
  app/src/main/java/io/homeassistant/companion/android/database/sensor/Sensor.kt
  app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorDao.kt
  app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorWithAttributes.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
Labels: cla-signed, enhancement, minor

#815 Fix wakelock error for requesting accurate location.
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationBroadcastReceiver.kt
Labels: bug, cla-signed, patch

#818 Use latest context in pressure and proximity sensor
  app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
Labels: bug, cla-signed, patch

#813 Add do not disturb sensor
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/DNDSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, enhancement, patch

#819 Sensor Crashes
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: bug, cla-signed, patch

#816 Hopefully fix the background location updates randomly stopping.
  app/src/full/java/io/homeassistant/companion/android/notifications/MessagingService.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorComponent.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/util/PermissionManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Labels: bug, cla-signed, patch

#824 Fix requests for accurate location on app open.
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Labels: bug, cla-signed, patch

#827 Lokalise: Translations update
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fy-rNL/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl-rNL/strings.xml
  app/src/main/res/values-pl-rPL/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: cla-signed, misc, patch

#832 Fix geocoded crash, report expected minimum accuracy for location
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Labels: bug, cla-signed, patch

#834 Fix location updates in the background
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Labels: cla-signed

#828 CI/CD Changes
  .github/release-drafter.yml
  .github/workflows/beta.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  README.md
Labels: cla-signed

#842 Bump some app dependencies
  buildSrc/src/main/kotlin/Config.kt
Labels: cla-signed

#843 Remove excess calls to setupLocationTracking
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed

#844 More build updates
  .github/workflows/beta.yml
  .github/workflows/release.yml
  app/build.gradle.kts
Labels: cla-signed

#845 Add link to companion docs under app configuration
  app/src/main/res/drawable/ic_question.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/preferences.xml
Labels: cla-signed

#837 Update instructions for running the project from the scratch
  README.md
Labels: cla-signed

#846 Sentry.io Changes
  .github/workflows/beta.yml
  .github/workflows/release.yml
  app/build.gradle.kts
  app/src/full/AndroidManifest.xml
Labels: cla-signed

#847 Add description for each sensor on details screen, only show device class and icon if they are set
  app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/DNDSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NextAlarmManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt
  app/src/main/res/layout/fragment_mobile_app_integration.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values-lv/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl-rNL/strings.xml
  app/src/main/res/values-pl-rPL/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/sensor_detail.xml
Labels: cla-signed

#850 Ensure the change-log is short for Google Play
  .github/workflows/beta.yml
  .github/workflows/release.yml
Labels: cla-signed
