Repository home-assistant/android, pull requests merged in 2021-11, with the labels that each got.

#1844 Convert wear home activity to compose
  wear/build.gradle.kts
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomeListAdapter.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/viewHolders/ButtonViewHolder.kt
  wear/src/main/java/io/homeassistant/companion/android/viewHolders/EntityButtonViewHolder.kt
  wear/src/main/java/io/homeassistant/companion/android/viewModels/EntityViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/viewModels/ViewModuleComponent.kt
  wear/src/main/res/drawable/ic_garage.xml
  wear/src/main/res/drawable/ic_light.xml
  wear/src/main/res/drawable/ic_scenes.xml
  wear/src/main/res/drawable/ic_scripts.xml
  wear/src/main/res/layout/activity_home.xml
  wear/src/main/res/layout/listitem_button.xml
  wear/src/main/res/layout/listitem_entity_button.xml
  wear/src/main/res/values/strings.xml
Labels: cla-signed, hacktoberfest-accepted, Wear OS

#1864 Add measured power setting to BLE transmitter
  app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconTransmitter.kt
  app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/TransmitterManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
  app/src/main/res/values/strings.xml
Labels: cla-signed

#1865 Dependency updates and minor changes to accompany them
  app/build.gradle.kts
  app/src/full/java/io/homeassistant/companion/android/settings/SettingsWearActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
Labels: cla-signed

#1835 Add support for entity category and state class sensors
  app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  app/src/main/java/io/homeassistant/companion/android/database/sensor/Sensor.kt
  app/src/main/java/io/homeassistant/companion/android/database/sensor/SensorWithAttributes.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/AppSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/AudioSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BatterySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/DNDSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/KeyguardSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LastUpdateManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/MobileDataManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NetworkSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PowerSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/TimeZoneManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/TrafficStatsManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/SensorRegistration.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/SensorRequest.kt
Labels: cla-signed, hacktoberfest-accepted

#1868 Move entities call back to presenter, use ToggleChip for toggle domains
  wear/build.gradle.kts
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/viewModels/EntityViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/viewModels/ViewModuleComponent.kt
Labels: cla-signed, Wear OS

#1869 Bump compose libraries
  app/build.gradle.kts
Labels: cla-signed

#1840 Replace kotlinx.android.synthetic with viewbinding
  app/build.gradle.kts
  app/src/full/java/io/homeassistant/companion/android/notifications/NotificationAction.kt
  app/src/full/java/io/homeassistant/companion/android/settings/SettingsWearActivity.kt
  app/src/main/java/io/homeassistant/companion/android/launch/my/MyActivity.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcEditFragment.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcReadFragment.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcWelcomeFragment.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcWriteFragment.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/SingleLiveEvent.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupFragment.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/manual_setup/ManualSetupActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/util/LoadingView.kt
Labels: cla-signed, hacktoberfest-accepted

#1870 Add a short delay and update entities again on wear homescreen
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
Labels: cla-signed, Wear OS

#1871 Fix version check.
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
Labels: cla-signed

#1873 Hotfix/fix startup crash
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed

#1867 fix warnings
  app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/StepsSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/util/LocationPermissionInfoHandler.kt
Labels: cla-needed

#1876 Request proper android 12 permissions for BLE transmitter
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
Labels: cla-signed

#1882 Remove automatic darkening of system bars
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
Labels: cla-signed

#1887 Bring back rotary input support for home screen using workaround
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/util/RotaryEventDispatcher.kt
Labels: cla-signed

#1875 Add settings and favorites for wear so users can quickly execute actions they do regularly faster
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  wear/build.gradle.kts
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/settings/SettingsComposable.kt
  wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
  wear/src/main/java/io/homeassistant/companion/android/viewModels/EntityViewModel.kt
  wear/src/main/res/values/strings.xml
Labels: cla-signed, Wear OS

#1886 Allow categories in Wear to be collapsed and expanded for easier navigation
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
Labels: cla-signed, Wear OS

#1884 Initial WebSocket Implementation
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidgetConfigureActivity.kt
  common/src/main/java/io/homeassistant/companion/android/common/dagger/AppComponent.kt
  common/src/main/java/io/homeassistant/companion/android/common/dagger/DataComponent.kt
  common/src/main/java/io/homeassistant/companion/android/common/dagger/DataModule.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantApis.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantRetrofit.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/authentication/AuthenticationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/ServiceFields.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationService.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/GetConfigResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/DomainResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/GetConfigResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/SocketResponse.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/viewModels/EntityViewModel.kt
Labels: cla-signed

#1894 Fixing Splash screen so it isn't blurry and adding rounded edges
  wear/src/main/res/drawable/logo.png
  wear/src/main/res/drawable/logo_rounded.png
  wear/src/main/res/drawable/splash_background.xml
Labels: cla-signed, Wear OS

#1895 Major Wear Cleanup
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/ListHeader.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/OtherSection.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/settings/SettingsComposable.kt
  wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
  wear/src/main/java/io/homeassistant/companion/android/viewModels/EntityViewModel.kt
Labels: cla-signed, Wear OS

#1896 Fixing splash screen Wear OS
  wear/src/main/res/drawable/logo_rounded.png
  wear/src/main/res/drawable/splash_background.xml
  wear/src/main/res/drawable/splash_logo.png
Labels: cla-signed, Wear OS

#1900 Add the time, make better use of list headers on Wear
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/ListHeader.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/OtherSection.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
Labels: cla-signed, Wear OS

#1899 Load a temporary favorite chip for each entity ID until we get entities
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
Labels: cla-signed, Wear OS

#1901 Add preview functions for easy UI tweaking in Android Studio
  wear/build.gradle.kts
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/ListHeader.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/OtherSection.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
Labels: cla-signed, Wear OS

#1902 Clean up welcome and notification details compose views
  app/src/main/java/io/homeassistant/companion/android/onboarding/WelcomeFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/views/WelcomeView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/views/NotificationDetailView.kt
  app/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
Labels: cla-signed

#1842 Wear OS shortcut Tile
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  wear/build.gradle.kts
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/data/SimplifiedEntity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/ListHeader.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/TileActionActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/TilesComponent.kt
  wear/src/main/res/drawable/favorite_entities_tile_example.png
  wear/src/main/res/values/strings.xml
Labels: cla-signed, hacktoberfest-accepted, Wear OS

#1906 Initial support for websocket state changed events!
  app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/EventResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/SocketResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/StateChangedEvent.kt
Labels: cla-signed

#1907 Wear OS Instant Updates
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
  wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
Labels: cla-signed

#1912 Sort entities, add time and headers in wear settings
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
  wear/src/main/res/values/strings.xml
Labels: cla-signed

#1913 Use default trigger range if field is left blank for high accuracy mode
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Labels: cla-signed

#1914 Check cover state in QS tiles
  app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
Labels: cla-signed

#1919 Add sorting, split by category, add collapsing categories
  wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
  wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
Labels: cla-signed

#1926 Wear OS tile: Fix default icon and move to broadcast receiver
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/TileActionReceiver.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/TilesComponent.kt
Labels: cla-signed, Wear OS

#1931 Get dependabot to run daily
  .github/dependabot.yml
Labels: cla-signed

#1938 Add launch screen for phone app
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/onboarding/views/WelcomeView.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
  app/src/main/res/drawable-v26/launch_screen_background.xml
  app/src/main/res/drawable/app_icon.xml
  app/src/main/res/drawable/app_icon_round.jpg
  app/src/main/res/drawable/launch_screen_background.xml
  app/src/main/res/layout/widget_camera.xml
  app/src/main/res/layout/widget_media_controls.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-v31/styles.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/preferences.xml
Labels: cla-signed

#1939 Change navigation bar background color to be the same as the app's background color
  app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
Labels: cla-signed

#1909 Change splash screen icon
  wear/src/main/res/drawable/splash_background.xml
  wear/src/main/res/drawable/splash_logo.png
Labels: cla-signed, Wear OS

#1940 Allow the websocket to reconnect
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Labels: cla-signed

#1941 Remove startup activity animation
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
Labels: cla-signed

#1942 Fix forwarding HA instance to wear after phone settings introduction
  app/src/full/res/values/wear.xml
  app/src/main/res/values/wear.xml
Labels: cla-signed, Wear OS

#1944 Instant Update Widgets
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/DataModule.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Labels: cla-signed

#1946 Bump wear libraries
  wear/build.gradle.kts
Labels: cla-signed, Wear OS

#1951 Fix default icon for shortcut tile
  wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
Labels: cla-signed, Wear OS

#1956 Fix NFC crash when inside read fragment
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
Labels: cla-signed

#1960 Add haptic feedback to wear shortcut tile
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/tiles/TileActionReceiver.kt
Labels: cla-signed

#1908 Editing wear favorites from the phone
  app/build.gradle.kts
  app/src/full/java/io/homeassistant/companion/android/settings/SettingsWearActivity.kt
  app/src/full/java/io/homeassistant/companion/android/settings/SettingsWearViewModel.kt
  app/src/full/java/io/homeassistant/companion/android/settings/views/SettingsWearFavoritesView.kt
  app/src/full/java/io/homeassistant/companion/android/settings/views/SettingsWearHomeView.kt
  app/src/full/java/io/homeassistant/companion/android/settings/views/SettingsWearLandingView.kt
  app/src/full/java/io/homeassistant/companion/android/settings/views/SettingsWearMainView.kt
  app/src/full/res/values/wear.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
  app/src/main/res/values/strings.xml
  app/src/minimal/java/io/homeassistant/companion/android/settings/views/SettingsWearMainView.kt
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
  wear/src/main/res/values/wear.xml
Labels: cla-signed, Wear OS

#1962 Multiple Bug Fixes
  app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
Labels: cla-signed

#1959 Wear os add lock domain
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/TileActionReceiver.kt
  wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
  wear/src/main/res/values/strings.xml
Labels: cla-signed

#1972 Fix Websocket crash when we don't get exactly what we expected.
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Labels: cla-signed

#1970 Wear redesign
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/ChooseEntityView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/ListHeader.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/OtherSection.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/TimeText.kt
  wear/src/main/java/io/homeassistant/companion/android/theme/Color.kt
  wear/src/main/java/io/homeassistant/companion/android/theme/Theme.kt
  wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
  wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
Labels: cla-signed, Wear OS
