Repository home-assistant/android, pull requests merged in 2022-10, with the labels that each got.

#2937 Update change log week of 10/1
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#2930 Update iBeacon format to have underscores
  app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconNameFormat.kt
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#2894 Add commands to control screen brightness and a sensor to get its value
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/DisplaySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#2902 Fix websocket subscription race/dropping first message
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRequest.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Labels: cla-signed

#2922 Show custom icon if set for the entity in device controls
  app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt
  common/src/main/res/values/colors.xml
Labels: cla-signed

#2923 Simplify themes
  app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/themes/ThemesManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/res/values/arrays.xml
  common/src/main/res/values/strings.xml
Labels: cla-signed

#2924 Add new force_on and force_off options to command_high_accuracy_mode.
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed

#2934 Update Gradle to 7.5.1, Android Gradle plugin to 7.3.0
  app/build.gradle.kts
  app/src/full/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  common/build.gradle.kts
  common/src/main/AndroidManifest.xml
  gradle/wrapper/gradle-wrapper.properties
  wear/build.gradle.kts
  wear/src/main/AndroidManifest.xml
Labels: cla-signed

#2936 Default to app icon if icon is not available for notification
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed

#2939 Bump Hilt version to 2.44
  app/build.gradle.kts
  build.gradle.kts
  common/build.gradle.kts
  wear/build.gradle.kts
Labels: cla-signed

#2938 Update change log week of 10/1 for beta
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#2940 Set the media player widget icon if available, otherwise default to cast icon
  app/src/main/java/io/homeassistant/companion/android/widgets/media_player_controls/MediaPlayerControlsWidget.kt
Labels: cla-signed

#2682 Android 13 notification changes + target
  app/build.gradle.kts
  app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
  app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardApp.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/res/drawable/ic_notification_off.xml
  app/src/main/res/xml/preferences.xml
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
Labels: cla-signed

#2868 Add notify command for app-lock
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed

#2942 Use compressed entity changes for device controls
  app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/CompressedEntity.kt
Labels: cla-signed

#2952 Clean up spacing in BLE transmitter description
  common/src/main/res/values/strings.xml
Labels: cla-signed, Hacktoberfest

#2956 Add permissions requests to wear OS sensors and add network sensors
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorsView.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, Wear OS, Hacktoberfest, WTH

#2958 Don't use a hardcoded list of apps for Wear OS detection
  app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearDetection.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/minimal/java/io/homeassistant/companion/android/settings/wear/SettingsWearDetection.kt
Labels: cla-signed, Hacktoberfest

#2959 Update deprecated onBackPressed, support predictive back gesture
  app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed, Hacktoberfest

#2960 Add a screen off timeout sensor and command for control
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/DisplaySensorManager.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Hacktoberfest

#2968 Show settings chip while loading Wear app
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
Labels: cla-signed, Wear OS, Hacktoberfest

#2978 Breaking Change: Fix mobile data roaming sensor after target SDK change
  app/src/main/java/io/homeassistant/companion/android/sensors/MobileDataManager.kt
Labels: cla-signed, Hacktoberfest

#2926 Settings activity app lock
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/main/res/layout/activity_settings.xml
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
Labels: cla-signed

#2961 Add On Body sensor for Wear OS
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/sensors/OnBodySensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, Wear OS, Hacktoberfest

#2969 Support zone name only location tracking
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/UpdateLocation.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/ZoneAttributes.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/UpdateLocationRequest.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Hacktoberfest

#2979 Tweak onboarding design to be more unified
  app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardApp.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingHeaderView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionView.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Hacktoberfest

#2983 Change log 10/21
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed, Hacktoberfest

#2980 Improve monochrome icon
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/drawable/ic_launcher_monochrome.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: cla-signed, Hacktoberfest

#2962 Convert Play tasks to coroutines
  app/build.gradle.kts
  app/src/full/java/io/homeassistant/companion/android/onboarding/WearOnboardingListener.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantApis.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
  wear/build.gradle.kts
  wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
Labels: cla-signed, Hacktoberfest

#2984 Add previews to Wear OS compose and sort sensor by name
  wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/RefreshIntervalPickerView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorManagerUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/TemplateTileSettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/TimeText.kt
  wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
Labels: cla-signed, Wear OS, Hacktoberfest

#2987 Make more onboarding screens scrollable
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupView.kt
Labels: cla-signed, Hacktoberfest

#2988 Fix navigation bar color on OnboardingActivity
  app/src/main/AndroidManifest.xml
Labels: cla-signed, Hacktoberfest

#2989 Revert/set force dark again for webview
  app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/themes/ThemesManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed, Hacktoberfest

#2991 Remove dependency that caused beta to fail to publish.
  app/build.gradle.kts
Labels: cla-signed, Hacktoberfest

#2994 Add Wet Mode Sensor
  common/src/main/res/values/strings.xml
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/WetModeSensorManager.kt
Labels: cla-signed, Wear OS, Hacktoberfest

#2995 Add user activity sensor from health services for Wear OS
  common/src/main/res/values/strings.xml
  wear/build.gradle.kts
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, Wear OS, Hacktoberfest

#2999 Bump play services location tracking and move away from deprecated methods
  app/build.gradle.kts
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Labels: cla-signed, Hacktoberfest

#3000 Add database checks to PR workflow
  .github/workflows/pr.yml
Labels: cla-signed, Hacktoberfest

#3002 Remove unused setters
  app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconMonitor.kt
  app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconNameFormat.kt
  app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconTransmitter.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorListView.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/CheckRateLimits.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/RateLimitResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/RegisterDeviceRequest.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/RegisterDeviceResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/GetConfigResponse.kt
  common/src/main/java/io/homeassistant/companion/android/database/authentication/Authentication.kt
  common/src/main/java/io/homeassistant/companion/android/database/notification/NotificationDao.kt
  common/src/main/java/io/homeassistant/companion/android/database/sensor/Attribute.kt
  common/src/main/java/io/homeassistant/companion/android/database/sensor/Sensor.kt
  common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorWithAttributes.kt
  wear/src/main/java/io/homeassistant/companion/android/data/SimplifiedEntity.kt
Labels: cla-signed, Hacktoberfest

#3009 Set focus for onboarding activity to support rotary input
  wear/src/main/res/layout/activity_onboarding.xml
Labels: cla-signed, Wear OS, Hacktoberfest

#3008 Add a heart rate sensor to Wear OS
  common/src/main/res/values/strings.xml
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, Wear OS, Hacktoberfest

#3013 Update change log 10/28
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed, Hacktoberfest
