Repository home-assistant/android, pull requests merged in 2022-11, with the labels that each got.

#3015 Only use internal URL when data is also using Wi-Fi
  app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/ssid/views/SsidView.kt
  common/src/main/AndroidManifest.xml
  common/src/main/java/io/homeassistant/companion/android/common/data/DataModule.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelper.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelperImpl.kt
Labels: cla-signed, hacktoberfest-accepted, Hacktoberfest

#3017 Change DocsLink in Wear OS Sensors
  wear/src/main/java/io/homeassistant/companion/android/sensors/BedtimeModeSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/OnBodySensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/TheaterModeSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/WetModeSensorManager.kt
Labels: cla-signed, hacktoberfest-accepted, Wear OS, Hacktoberfest

#3021 Catch Geocoder exceptions on Android 13
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
Labels: cla-signed, hacktoberfest-accepted, Hacktoberfest

#3023 Only resume once for websocket message responses
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Labels: cla-signed, hacktoberfest-accepted, Hacktoberfest

#3025 Don't check Wifi SSID when home wifi list is empty
  common/src/main/java/io/homeassistant/companion/android/common/data/url/UrlRepositoryImpl.kt
Labels: cla-signed, Hacktoberfest

#3027 Increase notification video attachment GIF length
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed, Hacktoberfest

#3030 Fix location updates on core <2022.2
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/entities/UpdateLocationRequest.kt
Labels: cla-signed

#3031 Don't log full exception with no Wear app installed
  app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearDetection.kt
Labels: cla-signed

#3028 Bump and switch to compose BOM dependency
  app/build.gradle.kts
  build.gradle.kts
  common/build.gradle.kts
  wear/build.gradle.kts
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorsView.kt
Labels: cla-signed

#3035 Revert reorderable bump until upstream issue is fixed
  app/build.gradle.kts
Labels: cla-signed

#2982 Add caching of favorites in Wear OS, resulting in prettier loading
  common/schemas/io.homeassistant.companion.android.database.AppDatabase/34.json
  common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  common/src/main/java/io/homeassistant/companion/android/database/DatabaseModule.kt
  common/src/main/java/io/homeassistant/companion/android/database/wear/FavoriteCaches.kt
  common/src/main/java/io/homeassistant/companion/android/database/wear/FavoriteCachesDao.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
Labels: cla-signed, hacktoberfest-accepted, Wear OS, Hacktoberfest

#3005 Add daily floors sensor for Wear OS3 devices
  app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/BluetoothSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/DevicePolicyManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/DisplaySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/DynamicColorSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/KeyguardSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LastAppSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LastRebootSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/MobileDataManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PhoneStateSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/QuestSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/TimeZoneManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/TrafficStatsManager.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorListView.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/AppSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/AudioSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/DNDSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/LastUpdateManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/NextAlarmManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/PowerSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/StepsSensorManager.kt
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorManagerUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorUi.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/BedtimeModeSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/OnBodySensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/TheaterModeSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/WetModeSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/util/PreviewData.kt
Labels: cla-signed, hacktoberfest-accepted, Wear OS, Hacktoberfest

#3026 Track time between hardware sensor updates to restart the listener as needed
  app/src/main/java/io/homeassistant/companion/android/sensors/LightSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/PressureSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/ProximitySensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/StepsSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/OnBodySensorManager.kt
Labels: cla-signed, Hacktoberfest

#3039 Remove unneeded kotlin option
  wear/build.gradle.kts
Labels: cla-signed, Wear OS

#3042 Add missing boot completed permission for Wear OS
  wear/src/main/AndroidManifest.xml
Labels: cla-signed, Wear OS

#3046 Catch exceptions while sending websocket messages
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Labels: cla-signed

#3052 Remove quick bar deprecation comment
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed

#3045 Switch from `viewModelScope` to `lifecycleScope` for external collections
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
Labels: cla-signed, Wear OS

#3054 Add Daily Calories, Distance and Steps sensors for health services
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
Labels: cla-signed, Wear OS

#3056 Bump location dependency
  app/build.gradle.kts
Labels: cla-signed

#3058 Update change log week of 11/11
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3061 Make active websocket message tracking thread-safe
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Labels: cla-signed

#3077 Revert jackson-module-kotlin bump to fix compatibility on older Android version
  app/build.gradle.kts
  common/build.gradle.kts
  wear/build.gradle.kts
Labels: cla-signed

#3079 Add proper device class for daily distance sensor on Wear OS3
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
Labels: cla-signed, Wear OS

#3080 Update and fix in-app language picker
  .github/actions/download-translations/action.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/BaseActivity.kt
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/language/LanguagesManager.kt
  app/src/main/java/io/homeassistant/companion/android/settings/language/LanguagesProvider.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  common/src/main/res/xml/locales_config.xml
Labels: cla-signed

#3081 Skip heart rate value updates when below 0
  wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
Labels: cla-signed, Wear OS

#3087 Reduce usage of job scheduling to avoid throttling
  app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/bluetooth/ble/IBeaconMonitor.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/OnBodySensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed

#3092 Update a bunch of Github Actions
  .github/actions/create-release-number/action.yml
  .github/workflows/beta.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: cla-signed

#3097 Button Widget: Hide label if empty or null
  app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
Labels: cla-signed

#3099 Button Widget: Uniform Spacing
  app/src/main/res/layout/widget_button.xml
  app/src/main/res/layout/widget_static.xml
Labels: cla-signed

#3102 Support automation entities in quick settings tiles
  app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
Labels: cla-signed

#3104 Fix current version sensor so it properly reports the flavor
  app/src/main/java/io/homeassistant/companion/android/sensors/AppSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/AppSensorManagerBase.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/AppSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed

#3105 Add deeplinks to Wear OS sensor sync notifications
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, Wear OS

#3108 Don't crash when system is unable to handle download intent
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed

#3109 Only request multiple tasks for HA notification intents
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed

#3114 Remove NFC tag sample YAML for 'scanned by this device' on 2022.12+
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/views/NfcEditView.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/views/NfcNavigationView.kt
Labels: cla-signed

#3111 Add some debug logs for heart rate sensor
  wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
Labels: cla-signed, Wear OS

#3103 Only subscribe to supported entities on Wear OS home screen
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
Labels: cla-signed, Wear OS

#3121 Update quick setting tiles with state updates
  app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
Labels: cla-signed
