Repository home-assistant/android, pull requests merged in 2022-12, with the labels that each got.

#3132 Add initial Matter commissioning support
  app/build.gradle.kts
  app/src/full/AndroidManifest.xml
  app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningActivity.kt
  app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningService.kt
  app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningViewModel.kt
  app/src/full/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
  app/src/full/java/io/homeassistant/companion/android/matter/views/MatterCommissioningView.kt
  app/src/full/java/io/homeassistant/companion/android/matter/views/MatterCommissioningViewPreviewStates.kt
  app/src/main/java/io/homeassistant/companion/android/matter/MatterFrontendCommissioningStatus.kt
  app/src/main/java/io/homeassistant/companion/android/matter/MatterManager.kt
  app/src/main/java/io/homeassistant/companion/android/matter/MatterModule.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragmentFactory.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/main/res/drawable/ic_matter.xml
  app/src/minimal/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRequest.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3133 Update change log week of 12/3
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3139 Revert "Bump actions/setup-java from 3.6.0 to 3.7.0"
  .github/workflows/beta.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/weekly.yaml
Labels: cla-signed

#3123 Add new option to vibrate when quick settings tile is clicked
  app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
  common/schemas/io.homeassistant.companion.android.database.AppDatabase/35.json
  common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  common/src/main/java/io/homeassistant/companion/android/database/qs/TileEntity.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3126 Restart health services if no updates received in 30 minutes
  wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
Labels: cla-signed, Wear OS

#3131 Fix monochrome icon on Android 13+
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
Labels: cla-signed

#3157 Update change log week of 12/16
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3115 Migrate more sensors to Wear OS
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/DisplaySensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/KeyguardSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/LastRebootSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/LightSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/MobileDataManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/PressureSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/ProximitySensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/StorageSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/TimeZoneManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/TrafficStatsManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, Wear OS

#3158 Add a tile to start a conversation
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/ConversationResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/ConversationSpeechPlainResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/ConversationSpeechResponse.kt
  common/src/main/res/values/strings.xml
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/ConversationTile.kt
  wear/src/main/res/drawable/conversation_tile_example.png
Labels: cla-signed

#3160 Use entity icon for quick settings tiles by default
  app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
  common/build.gradle.kts
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/complications/EntityStateDataSourceService.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
  wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
  wear/src/main/java/io/homeassistant/companion/android/views/ChooseEntityView.kt
Labels: cla-signed

#3024 Add setting to start the app always on the first dashboard view
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/util/LifecycleHandler.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/main/res/xml/preferences.xml
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, hacktoberfest-accepted, Hacktoberfest

#3161 Matter dependency update and tweaks for shared devices + errors
  app/build.gradle.kts
  app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningActivity.kt
  app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningService.kt
  app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningViewModel.kt
  app/src/full/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
  app/src/full/java/io/homeassistant/companion/android/matter/views/MatterCommissioningView.kt
  app/src/full/java/io/homeassistant/companion/android/matter/views/MatterCommissioningViewPreviewStates.kt
  app/src/main/java/io/homeassistant/companion/android/matter/MatterManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/minimal/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/MatterCommissionResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/SocketResponse.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3162 Add support for publishing to Amazon on release.
  .github/workflows/beta.yml
  .github/workflows/release.yml
Labels: cla-signed

#3163 Migrate to more recently updated Action.
  .github/workflows/beta.yml
Labels: cla-signed

#3165 Update change log 12/19
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3172 Migrate setup-java action to use Temurin
  .github/workflows/beta.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/weekly.yaml
Labels: cla-signed

#3173 Fix app lock bypass on home WiFi command, code style
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed

#3167 Update instead of cancel notification on replies
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
  common/src/main/java/io/homeassistant/companion/android/database/notification/NotificationDao.kt
Labels: cla-signed

#3185 More quick settings tiles when needed
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/qs/Tile13Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile14Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile15Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile16Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile17Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile18Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile19Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile20Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile21Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile22Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile23Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile24Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile25Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile26Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile27Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile28Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile29Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile30Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile31Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile32Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile33Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile34Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile35Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile36Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile37Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile38Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile39Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/Tile40Service.kt
  app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/TileSlot.kt
  app/src/main/res/values/arrays.xml
  common/src/main/java/io/homeassistant/companion/android/database/qs/TileDao.kt
  common/src/main/java/io/homeassistant/companion/android/database/qs/TileEntity.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3191 Sentry Config
  app/build.gradle.kts
  app/src/full/AndroidManifest.xml
  app/src/full/java/io/homeassistant/companion/android/CrashHandling.kt
Labels: cla-signed

#3189 Add option for unlocked only quick settings tiles
  app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
  common/schemas/io.homeassistant.companion.android.database.AppDatabase/36.json
  common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  common/src/main/java/io/homeassistant/companion/android/database/qs/TileEntity.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed
