Repository home-assistant/android, pull requests merged in 2023-12, with the labels that each got.

#4035 mobile_app_notification_cleared for wearos
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  common/src/main/AndroidManifest.xml
  common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationDeleteReceiver.kt
  common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed, Wear OS

#4039 Fix target temperature step attribute name error
  app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
Labels: cla-signed

#4047 Check controls while locked setting when using panel
  app/src/main/java/io/homeassistant/companion/android/controls/HaControlsPanelActivity.kt
Labels: cla-signed

#3924 Add Wear OS TLS client certificate authentication (TLS CCA) support
  app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearViewModel.kt
  app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardApp.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
  app/src/main/java/io/homeassistant/companion/android/util/TLSWebViewClient.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/DataModule.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/TLSHelper.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/keychain/KeyChainRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/keychain/KeyChainRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/keychain/KeyStoreRepositoryImpl.kt
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
Labels: cla-signed, Wear OS, Hacktoberfest

#4038 Bump various project dependencies
  gradle/libs.versions.toml
Labels: cla-signed

#4049 Migrate BuildConfig to Gradle Build Files
  app/build.gradle.kts
  automotive/build.gradle.kts
  common/build.gradle.kts
  gradle.properties
  wear/build.gradle.kts
Labels: cla-signed

#4051 Bump car app library dependency
  gradle/libs.versions.toml
Labels: cla-signed

#4058 Update change log week of 12/15
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#4066 Fix button widget authentication dismissed due to non-foreground window
  app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetAuthenticationActivity.kt
Labels: cla-signed

#4062 Suppress system Matter device discovery bottom sheet
  app/src/full/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
  app/src/main/java/io/homeassistant/companion/android/matter/MatterManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/minimal/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
Labels: cla-signed
