Repository home-assistant/android, pull requests merged in 2023-01, with the labels that each got.

#3192 Update changelog week of 12/31
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3200 Add missing phone permission to Wear manifest
  wear/src/main/AndroidManifest.xml
Labels: cla-signed

#3203 Try/catch for individual sensor updates
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
Labels: cla-signed

#3212 Update health services dependency
  wear/build.gradle.kts
Labels: cla-signed

#3218 Minor Android Auto improvements
  app/src/full/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  app/src/full/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
Labels: cla-signed

#3178 Add UUID filter to Beacon Monitor
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
  common/src/main/java/io/homeassistant/companion/android/common/bluetooth/ble/IBeaconMonitor.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/database/sensor/SensorSetting.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3216 Bump a bunch of dependencies.
  app/build.gradle.kts
  common/build.gradle.kts
  wear/build.gradle.kts
Labels: cla-signed

#3225 Bunch of Android Auto enhancements
  .github/workflows/beta.yml
  app/src/full/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  app/src/full/java/io/homeassistant/companion/android/vehicle/HaCarAppService.kt
  app/src/full/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
  app/src/full/java/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3227 Update change log week of 1/13
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3220 Fix beacon monitor not updating after move to common
  common/src/main/AndroidManifest.xml
  common/src/main/java/io/homeassistant/companion/android/common/bluetooth/ble/IBeaconMonitor.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorUpdateReceiver.kt
Labels: cla-signed

#3229 Update Compose theme adapter dependency
  app/build.gradle.kts
  app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningActivity.kt
  app/src/full/java/io/homeassistant/companion/android/matter/views/MatterCommissioningView.kt
  app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearHomeView.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/TagReaderActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/authentication/AuthenticationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/welcome/WelcomeFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/welcome/WelcomeView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/controls/ManageControlsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationChannelFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorUpdateFrequencyFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/url/ExternalUrlFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/websocket/WebsocketSettingFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsSettingsFragment.kt
  app/src/main/res/values/styles.xml
Labels: cla-signed

#3231 Fix conversation data response type
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/ConversationSpeechResponse.kt
Labels: cla-signed

#3228 Add and Android Auto sensor!
  app/src/full/java/io/homeassistant/companion/android/sensors/AndroidAutoSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/AndroidAutoSensorManager.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3221 Initial commit of notification support on Wear OS
  README.md
  app/build.gradle.kts
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  common/build.gradle.kts
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/DeviceRegistration.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt
  wear/build.gradle.kts
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/notifications/FirebaseCloudMessagingService.kt
  wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/MessagingToken.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
Labels: cla-signed, Wear OS

#3232 Skip showing connection prompt when loaded URL is local or api path
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed

#3233 Conversation tile design changes
  common/src/main/res/values/colors.xml
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
Labels: cla-signed, Wear OS

#3239 Wi-Fi sensor improvements
  common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
Labels: cla-signed

#3240 Add bluetooth skippable intents in case sensor is not enabled
  wear/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, Wear OS

#3241 Split app-level and server-level settings
  app/src/main/java/io/homeassistant/companion/android/controls/HaControlsProviderService.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsModule.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/controls/ManageControlsViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsView.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/preferences_server.xml
  common/src/main/java/io/homeassistant/companion/android/common/LocalStorageImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/DataModule.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/LocalStorage.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/WearPrefsRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/WearPrefsRepositoryImpl.kt
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/TemplateTile.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/TileActionReceiver.kt
Labels: cla-signed

#3244 Set Wear OAuth redirect URI automatically and catch exceptions
  common/src/main/java/io/homeassistant/companion/android/common/data/authentication/AuthenticationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationRepositoryImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingPresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/manual_setup/ManualSetupPresenterImpl.kt
Labels: cla-signed, Wear OS

#3246 Fix conversation tile vibrate after settings split
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
Labels: cla-signed

#3252 Fix scene and script Android Auto actions
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
Labels: cla-signed

#3247 Update change log week of 1/20
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3254 Make conversation activity launchable
  common/src/main/res/values/strings.xml
  wear/src/debug/res/mipmap-anydpi-v26/ic_assist_launcher.xml
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
  wear/src/main/res/drawable/ic_assist_launcher_foreground.xml
  wear/src/main/res/mipmap-anydpi-v26/ic_assist_launcher.xml
Labels: cla-signed, Wear OS

#3195 Migrated all table and column names to lower snake case
  common/schemas/io.homeassistant.companion.android.database.AppDatabase/37.json
  common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  common/src/main/java/io/homeassistant/companion/android/database/authentication/Authentication.kt
  common/src/main/java/io/homeassistant/companion/android/database/authentication/AuthenticationDao.kt
  common/src/main/java/io/homeassistant/companion/android/database/qs/TileDao.kt
  common/src/main/java/io/homeassistant/companion/android/database/qs/TileEntity.kt
  common/src/main/java/io/homeassistant/companion/android/database/settings/Setting.kt
  common/src/main/java/io/homeassistant/companion/android/database/wear/EntityStateComplications.kt
  common/src/main/java/io/homeassistant/companion/android/database/wear/EntityStateComplicationsDao.kt
  common/src/main/java/io/homeassistant/companion/android/database/widget/CameraWidgetEntity.kt
  common/src/main/java/io/homeassistant/companion/android/database/widget/MediaPlayerControlsWidgetDao.kt
  common/src/main/java/io/homeassistant/companion/android/database/widget/MediaPlayerControlsWidgetEntity.kt
Labels: cla-signed

#3262 Improve state for Android Auto: translate, timestamps
  app/src/full/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
Labels: cla-signed

#3253 Add ble transmitter and beacon monitor notification commands to Wear OS
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/notifications/DeviceCommands.kt
  common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt
  wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed, Wear OS

#3267 Change log week of 1/25
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3270 Only show not supported error after support check is complete and design tweaks
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
Labels: cla-signed, Wear OS

#3273 Allow navigation to sensors in android auto if they contain proper attributes
  app/src/full/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Labels: cla-signed, Android Auto

#3266 Add TTS notifications to Wear OS
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt
  common/src/main/java/io/homeassistant/companion/android/common/util/NotificationManagerExtensions.kt
  common/src/main/java/io/homeassistant/companion/android/common/util/TextToSpeech.kt
  wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed, Wear OS

#3281 Invalidate cache before updating camera widget
  app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
Labels: cla-signed

#3284 Add a watchface complication for Assist
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/complications/AssistDataSourceService.kt
  wear/src/main/java/io/homeassistant/companion/android/complications/ComplicationReceiver.kt
Labels: cla-signed, Wear OS
