Repository home-assistant/android, pull requests merged in 2023-06, with the labels that each got.

#3560 Align dependency versions and bump Google dependencies
  app/build.gradle.kts
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  automotive/build.gradle.kts
  build.gradle.kts
  common/build.gradle.kts
  wear/build.gradle.kts
Labels: cla-signed

#3561 Speed up cold start by skipping Jackson ObjectMapper if possible
  common/src/main/java/io/homeassistant/companion/android/database/server/ServerConnectionInfo.kt
Labels: cla-signed

#3562 Update Wear Scaffold usage to be more consistent
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorManagerUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetTileShortcutsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/TemplateTileSettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/TimeText.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/phoneinstall/PhoneInstallView.kt
Labels: cla-signed, Wear OS

#3581 Update change log for June
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3570 Move vehicle service to main to allow for minimal Automotive build
  .github/workflows/beta.yml
  .github/workflows/release.yml
  README.md
  app/build.gradle.kts
  app/src/main/java/io/homeassistant/companion/android/vehicle/ChangeServerScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/HaCarAppService.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/LoginScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/SwitchToDrivingOptimizedScreen.kt
  automotive/build.gradle.kts
  automotive/src/full/AndroidManifest.xml
  automotive/src/main/AndroidManifest.xml
Labels: cla-signed

#3572 Set Wear theme background color to black
  wear/src/main/java/io/homeassistant/companion/android/onboarding/phoneinstall/PhoneInstallView.kt
  wear/src/main/res/layout/activity_integration.xml
  wear/src/main/res/layout/activity_manual_setup.xml
  wear/src/main/res/layout/activity_onboarding.xml
  wear/src/main/res/layout/view_loading.xml
  wear/src/main/res/values/colors.xml
Labels: cla-signed, Wear OS

#3579 Expose docs for websocket Matter/Thread functions
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Labels: cla-signed

#3586 Update manifest for Matter commissioning
  app/src/full/AndroidManifest.xml
  automotive/src/full/AndroidManifest.xml
Labels: cla-signed

#3589 Implement native Assist
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/assist/AssistActivity.kt
  app/src/main/java/io/homeassistant/companion/android/assist/AssistViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/assist/ui/AssistMessage.kt
  app/src/main/java/io/homeassistant/companion/android/assist/ui/AssistSheetView.kt
  app/src/main/java/io/homeassistant/companion/android/assist/ui/AssistUiPipeline.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/res/values/styles.xml
  automotive/build.gradle.kts
  automotive/src/main/AndroidManifest.xml
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/AssistPipelineEvent.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/AssistPipelineListResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/AssistPipelineResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/ConversationAgentInfoResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/TtsOutputResponse.kt
  common/src/main/java/io/homeassistant/companion/android/common/util/AudioRecorder.kt
  common/src/main/java/io/homeassistant/companion/android/common/util/AudioUrlPlayer.kt
  common/src/main/java/io/homeassistant/companion/android/common/util/UtilModule.kt
  common/src/main/res/values-night/colors.xml
  common/src/main/res/values/colors.xml
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
Labels: cla-signed

#3606 Update change log week of 6/23
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3604 Update Wear Assist with continued conversations, pipelines
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/AssistMessage.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
Labels: cla-signed, Wear OS

#3607 Minor Assist UI feedback/changes
  app/src/main/java/io/homeassistant/companion/android/assist/AssistViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/assist/ui/AssistSheetView.kt
  app/src/main/java/io/homeassistant/companion/android/assist/ui/AssistUiPipeline.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/ConversationAgentInfoResponse.kt
Labels: cla-signed

#3608 Add intent filter for button to Wear Assist activity
  wear/src/main/AndroidManifest.xml
Labels: cla-signed, Wear OS

#3597 First attempt at a new release model.
  .github/actions/create-release-notes/action.yml
  .github/actions/create-release-number/action.yml
  .github/workflows/monthly.yaml
  .github/workflows/onPush.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .github/workflows/weekly.yaml
  .gitignore
  README.md
  app/build.gradle.kts
  automotive/build.gradle.kts
  build.gradle.kts
  common/build.gradle.kts
  settings.gradle.kts
  wear/build.gradle.kts
Labels: cla-signed

#3609 Supply entity ID if friendly name is empty in android auto
  app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
Labels: cla-signed, Android Auto

#3610 Hide devices that are home from the android auto navigation screen
  app/src/main/java/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
Labels: cla-signed, Android Auto

#3611 Use Assist pipeline STT/TTS on Wear OS
  app/src/main/java/io/homeassistant/companion/android/assist/AssistViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/assist/ui/AssistSheetView.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/TagReaderActivity.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/util/UrlHandler.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  common/build.gradle.kts
  common/src/main/java/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt
  common/src/main/java/io/homeassistant/companion/android/util/UrlUtil.kt
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
  wear/src/main/java/io/homeassistant/companion/android/util/KeepScreenOn.kt
Labels: cla-signed, Wear OS

#3612 Hide native mode UI from automotive play store builds
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Labels: cla-signed, Android Auto

#3614 Add troubleshooting menu to settings, with Thread credentials sync
  app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningViewModel.kt
  app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsModule.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/developer/DeveloperSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/developer/DeveloperSettingsPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/settings/developer/DeveloperSettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/developer/DeveloperSettingsView.kt
  app/src/main/java/io/homeassistant/companion/android/thread/ThreadManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/main/res/drawable/ic_bug_report.xml
  app/src/main/res/drawable/ic_thread.xml
  app/src/main/res/xml/preferences.xml
  app/src/main/res/xml/preferences_developer.xml
  app/src/minimal/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3615 Add shortcut for Assist
  app/src/debug/res/mipmap-anydpi-v26/ic_assist_launcher.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/util/compose/ExposedDropdownMenu.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/assist/AssistShortcutActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/assist/AssistShortcutView.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/assist/AssistShortcutViewModel.kt
  app/src/main/res/mipmap-anydpi-v26/ic_assist_launcher.xml
  common/src/main/res/drawable/ic_assist_launcher_foreground.xml
  common/src/main/res/values/strings.xml
  wear/src/main/res/drawable/ic_assist_launcher_foreground.xml
Labels: cla-signed

#3616 Add 'Manage assistants' button to native Assist
  app/src/main/java/io/homeassistant/companion/android/assist/AssistActivity.kt
  app/src/main/java/io/homeassistant/companion/android/assist/AssistViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/assist/ui/AssistSheetView.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3617 Make sure our credential files are ignored from SCM.
  .gitignore
Labels: cla-signed

#3624 Fix dirty SCM
  .github/actions/download-translations/action.yml
  .github/workflows/onPush.yml
  .gitignore
Labels: cla-signed

#3623 Hide a few GMS features unavailable on Automotive
  app/src/full/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
  app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearDetection.kt
  app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/DataModule.kt
Labels: cla-signed
