Repository home-assistant/android, pull requests merged in 2023-03, with the labels that each got.

#3381 Update Splash Screen due to new requirements
  wear/src/main/res/drawable/splash_background.xml
Labels: cla-signed

#3375 Make background transparent, remove resizing and set minimum size to 1x1 grid for camera widget
  app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
  app/src/main/res/drawable/widget_transparent_background.xml
  app/src/main/res/layout/widget_camera.xml
  app/src/main/res/xml/camera_widget_info.xml
Labels: cla-signed

#3380 Improve sensor re-registration on app version change for offline server
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
Labels: cla-signed

#3369 Use a foreground service for reliable beacon scanning in background
  common/src/main/java/io/homeassistant/companion/android/common/bluetooth/ble/MonitoringManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
  common/src/main/java/io/homeassistant/companion/android/common/util/AppNotifChannels.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3386 Use a black background for Wear OS onboarding screens
  wear/src/main/res/layout/activity_integration.xml
  wear/src/main/res/layout/activity_manual_setup.xml
  wear/src/main/res/layout/activity_onboarding.xml
  wear/src/main/res/layout/view_loading.xml
Labels: cla-signed, Wear OS

#3387 Update Play Store listing for upcoming play policy changes for Wear OS
  app/src/full/play/listings/en-US/full-description.txt
  app/src/full/play/listings/en-US/graphics/phone-screenshots/1.png
  app/src/full/play/listings/en-US/graphics/phone-screenshots/2.png
  app/src/full/play/listings/en-US/graphics/phone-screenshots/3.png
  app/src/full/play/listings/en-US/graphics/phone-screenshots/4.png
  app/src/full/play/listings/en-US/graphics/wear-screenshots/2.png
  app/src/full/play/listings/en-US/graphics/wear-screenshots/3.png
  app/src/full/play/listings/en-US/graphics/wear-screenshots/4.png
  app/src/full/play/listings/en-US/graphics/wear-screenshots/5.png
  wear/src/main/AndroidManifest.xml
Labels: cla-signed, Wear OS

#3388 Push Wear users to install app on phone
  common/src/main/res/values/strings.xml
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/phoneinstall/PhoneInstallActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/phoneinstall/PhoneInstallView.kt
Labels: cla-signed, Wear OS

#3392 Fix (potential) crashes when deleting a server
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchPresenterBase.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
Labels: cla-signed

#3393 Google dependency bumps
  app/build.gradle.kts
  wear/build.gradle.kts
Labels: cla-signed

#3391 Update change log week of 3/3
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3385 Update sensors when BLE transmitter turned on and off
  common/src/main/java/io/homeassistant/companion/android/common/notifications/DeviceCommands.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
Labels: cla-signed

#3403 Update default entity icons
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
Labels: cla-signed

#3405 Update issue template selection
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla-signed

#3407 Allow clickAction to be set to noAction to do nothing
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed

#3398 Fix listed beacons that are out of range after enable
  common/src/main/java/io/homeassistant/companion/android/common/bluetooth/ble/IBeaconMonitor.kt
  common/src/main/java/io/homeassistant/companion/android/common/bluetooth/ble/MonitoringManager.kt
Labels: cla-signed

#3409 Move away from runBlocking and fix some bugs in geofence updates and clearing notification
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/NotificationDeleteReceiver.kt
Labels: cla-signed

#3411 Properly handle multiple permissions requests
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed, cla-error

#3414 Drop 'tile' from template tile name
  common/src/main/res/values/strings.xml
  wear/src/main/AndroidManifest.xml
Labels: cla-signed, Wear OS

#3413 Update change log week of 3/10
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3410 Server trust feature
  app/src/full/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/settings/server/ServerSettingsPresenterImpl.kt
  app/src/main/res/drawable/ic_settings_remote.xml
  app/src/main/res/xml/preferences_server.xml
  app/src/minimal/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed

#3416 Use new auth/revoke endpoint
  common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/authentication/impl/AuthenticationService.kt
Labels: cla-signed

#3417 Get user information and prevent using admin-only calls
  app/src/full/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
  app/src/full/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
  app/src/full/java/io/homeassistant/companion/android/matter/views/MatterCommissioningView.kt
  app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
  app/src/main/java/io/homeassistant/companion/android/launch/LaunchActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/minimal/java/io/homeassistant/companion/android/launch/LaunchPresenterImpl.kt
  common/schemas/io.homeassistant.companion.android.database.AppDatabase/39.json
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/CurrentUserResponse.kt
  common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  common/src/main/java/io/homeassistant/companion/android/database/server/Server.kt
  common/src/main/java/io/homeassistant/companion/android/database/server/ServerUserInfo.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingPresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupPresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
Labels: cla-signed

#3437 Add background to Wear screenshots
  app/src/full/play/listings/en-US/graphics/wear-screenshots/1.png
  app/src/full/play/listings/en-US/graphics/wear-screenshots/3.png
  app/src/full/play/listings/en-US/graphics/wear-screenshots/4.png
  app/src/full/play/listings/en-US/graphics/wear-screenshots/5.png
Labels: cla-signed

#3447 Make sure release keys are inflated.
  .github/actions/inflate-secrets/action.yml
Labels: cla-signed
