Repository home-assistant/android, pull requests merged in 2023-07, with the labels that each got.

#3625 Support sensor display precision
  app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/EntityRegistryResponse.kt
  wear/src/main/java/io/homeassistant/companion/android/complications/EntityStateDataSourceService.kt
Labels: cla-signed

#3626 Update change log week of 6/30
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3627 Bump dependency versions.
  app/build.gradle.kts
  automotive/build.gradle.kts
  build.gradle.kts
  common/build.gradle.kts
  wear/build.gradle.kts
Labels: cla-signed

#3628 Fix monthly tag
  .github/workflows/monthly.yaml
Labels: cla-signed

#3631 Jetpack Compose icon dialog
  app/build.gradle.kts
  app/src/main/assets/mdi_id_map.json
  app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/views/ManageShortcutsView.kt
  app/src/main/java/io/homeassistant/companion/android/util/icondialog/IIconKt.kt
  app/src/main/java/io/homeassistant/companion/android/util/icondialog/IconDialog.kt
  app/src/main/java/io/homeassistant/companion/android/util/icondialog/IconDialogFragment.kt
  app/src/main/java/io/homeassistant/companion/android/util/icondialog/IconDialogGrid.kt
  app/src/main/java/io/homeassistant/companion/android/util/icondialog/IconDialogSearch.kt
  app/src/main/java/io/homeassistant/companion/android/util/icondialog/IconFilter.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
  automotive/build.gradle.kts
  common/schemas/io.homeassistant.companion.android.database.AppDatabase/41.json
  common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  common/src/main/java/io/homeassistant/companion/android/database/IconDialogCompat.kt
  common/src/main/java/io/homeassistant/companion/android/database/qs/TileEntity.kt
  common/src/main/java/io/homeassistant/companion/android/database/widget/ButtonWidgetEntity.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3640 Implement suggestion area in app settings
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsHomeSuggestion.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsSuggestionPreference.kt
  app/src/main/res/drawable/ic_comment_processing_outline.xml
  app/src/main/res/drawable/preference_suggestion_background.xml
  app/src/main/res/layout/preference_suggestion.xml
  app/src/main/res/xml/preferences.xml
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
  common/src/main/res/values/colors.xml
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3642 Add Android Auto notification extension
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/util/NotificationManagerExtensions.kt
  common/src/main/java/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt
  common/src/main/java/io/homeassistant/companion/android/common/util/NotificationManagerExtensions.kt
  common/src/main/res/drawable-hdpi/ic_stat_ic_notification.png
  common/src/main/res/drawable-mdpi/ic_stat_ic_notification.png
  common/src/main/res/drawable-xhdpi/ic_stat_ic_notification.png
  common/src/main/res/drawable-xxhdpi/ic_stat_ic_notification.png
  common/src/main/res/drawable-xxxhdpi/ic_stat_ic_notification.png
  common/src/main/res/drawable/ic_stat_ic_notification.xml
Labels: cla-signed, Android Auto

#3643 Update change log week of 7/7
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3644 Fix broken Wear OS docs link in settings
  app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearActivity.kt
Labels: cla-signed

#3647 Minor update to Auto(motive) login screen
  app/src/main/java/io/homeassistant/companion/android/vehicle/LoginScreen.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Android Auto

#3646 Don't show assistant app suggestion on L, show on M
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
Labels: cla-signed

#3652 Force update on media session sensor when a session is in progress
  app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
Labels: cla-signed

#3654 Assistant app intent fallback to 'safe' intent if not found
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
Labels: cla-signed

#3653 Implement a frontend-like single entity picker
  app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
  app/src/main/java/io/homeassistant/companion/android/util/compose/SingleEntityPicker.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3657 Hide android auto sensor section from devices that do not support it
  app/src/full/java/io/homeassistant/companion/android/sensors/AndroidAutoSensorManager.kt
Labels: cla-signed

#3660 Update change log week of 7/14
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3399 Add CarInfo sensors
  app/build.gradle.kts
  app/src/full/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/HaCarAppService.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Android Auto

#3661 Update/replace deprecations in app module
  app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt
  app/src/full/java/io/homeassistant/companion/android/onboarding/WearOnboardingListener.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/controls/CameraControl.kt
  app/src/main/java/io/homeassistant/companion/android/controls/DefaultButtonControl.kt
  app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
  app/src/main/java/io/homeassistant/companion/android/controls/HaFailedControl.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NFCUtil.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/NotificationDeleteReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionView.kt
  app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LastAppSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorWorker.kt
  app/src/main/java/io/homeassistant/companion/android/settings/controls/ManageControlsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/language/LanguagesProvider.kt
  app/src/main/java/io/homeassistant/companion/android/settings/log/LogFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationChannelFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationHistoryFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/views/NotificationChannelView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/views/NotificationDetailView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorUpdateFrequencyFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/websocket/WebsocketSettingFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/widgets/views/ManageWidgetsView.kt
  app/src/main/java/io/homeassistant/companion/android/util/ContextExtensions.kt
  app/src/main/java/io/homeassistant/companion/android/util/DataUriDownloadManager.kt
  app/src/main/java/io/homeassistant/companion/android/util/OnSwipeListener.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
  app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
  common/src/main/java/io/homeassistant/companion/android/common/util/TextUtil.kt
  wear/src/main/java/io/homeassistant/companion/android/views/ChooseEntityView.kt
Labels: cla-signed

#3662 Use new entity picker for more settings
  app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearFavoritesView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/views/ManageShortcutsView.kt
  app/src/main/java/io/homeassistant/companion/android/util/compose/SingleEntityPicker.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3663 Add toggle for Assist as assistant app on Wear
  common/src/main/res/values/strings.xml
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
Labels: cla-signed, Wear OS

#3669 Breaking change: support last_used/preferred pipeline IDs and use last_used by default
  app/src/main/java/io/homeassistant/companion/android/assist/AssistActivity.kt
  app/src/main/java/io/homeassistant/companion/android/assist/AssistViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/assist/AssistShortcutView.kt
  common/src/main/java/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
Labels: cla-signed

#3676 Update Thread network sync to update/delete HA networks
  app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
  app/src/main/java/io/homeassistant/companion/android/settings/developer/DeveloperSettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/thread/ThreadManager.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3668 Send state based on reported status, apply car prefix to car sensors, add some logging around new car sensors
  app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Android Auto

#3685 Only show unit of measurement if we have it and if the state is not a string while managing sensors
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorListView.kt
Labels: cla-signed

#3686 Don't send group summary notifications to Android Auto
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed, Android Auto

#3687 Only add up to the allowed limit of list items to android auto
  app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
Labels: cla-signed, Android Auto

#3688 Add sensors to report car energy profile
  app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Android Auto

#3670 Add favorites selection for Android Auto
  app/build.gradle.kts
  app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearFavoritesView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/vehicle/ManageAndroidAutoSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/vehicle/ManageAndroidAutoViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/vehicle/views/AndroidAutoFavoritesView.kt
  app/src/main/java/io/homeassistant/companion/android/util/compose/FavoriteEntityRow.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/HaCarAppService.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
  app/src/main/res/drawable/ic_car.xml
  app/src/main/res/xml/preferences.xml
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Android Auto

#3692 Resume Assist voice input on new intent (as assistant app/brought to front)
  app/src/main/java/io/homeassistant/companion/android/assist/AssistActivity.kt
  app/src/main/java/io/homeassistant/companion/android/assist/AssistViewModel.kt
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
Labels: cla-signed

#3693 Text field consistency updates
  app/src/main/java/io/homeassistant/companion/android/nfc/views/NfcWriteView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/views/ManageTilesView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/views/ManageShortcutsView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/ssid/views/SsidView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/url/views/ExternalUrlInputView.kt
  app/src/main/java/io/homeassistant/companion/android/util/compose/ExposedDropdownMenu.kt
  app/src/main/java/io/homeassistant/companion/android/util/compose/ServerDropdownButton.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/assist/AssistShortcutView.kt
Labels: cla-signed

#3691 Update change log week of 7/21
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3695 Match android auto dependency versions
  app/build.gradle.kts
Labels: cla-signed, Android Auto

#3698 Update/replace deprecations in common module
  common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelperImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/AudioSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/TrafficStatsManager.kt
Labels: cla-signed

#3705 Use WifiManager deprecations again for instant 'location' info
  common/src/main/java/io/homeassistant/companion/android/common/data/wifi/WifiHelperImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
Labels: cla-signed

#3706 Fix Wear more details crash with Kelvin light temperature
  common/src/main/res/values/strings.xml
Labels: cla-signed, Wear OS

#3703 Show measurement unit in Wear OS complication
  common/schemas/io.homeassistant.companion.android.database.AppDatabase/42.json
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
  common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  common/src/main/java/io/homeassistant/companion/android/database/wear/EntityStateComplications.kt
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/complications/ComplicationConfigViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/complications/EntityStateDataSourceService.kt
  wear/src/main/java/io/homeassistant/companion/android/complications/views/ComplicationConfigMainView.kt
Labels: cla-signed, Wear OS

#3694 Android auto: Switch to GridTemplate for home screen and default to favorites if defined
  app/src/main/java/io/homeassistant/companion/android/util/vehicle/GridItems.kt
  app/src/main/java/io/homeassistant/companion/android/util/vehicle/NativeModeActionStrip.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/BaseVehicleScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/DomainListScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
Labels: cla-signed, Android Auto

#3717 Fix version code for F-Droid builds
  .github/workflows/onPush.yml
Labels: cla-signed

#3718 Bump some project dependencies
  app/build.gradle.kts
  automotive/build.gradle.kts
  wear/build.gradle.kts
Labels: cla-signed

#3725 Add navigation entities to favorites and convert nav screen to grid
  app/src/main/java/io/homeassistant/companion/android/settings/vehicle/ManageAndroidAutoViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/vehicle/views/AndroidAutoFavoritesView.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
Labels: cla-signed, Android Auto

#3726 Update sensors when driving interface is open or resumed
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Labels: cla-signed, Android Auto

#3728 Fix old server references in app-level preferences
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/servers/ServerManagerImpl.kt
Labels: cla-signed

#3729 Show favorites only if selected server has favorites
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Labels: cla-signed, Android Auto

#3723 Smarter discovery for already added instances
  app/src/full/java/io/homeassistant/companion/android/settings/wear/views/SettingsWearMainView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardApp.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryFragment.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantInstance.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/HomeAssistantSearcher.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
Labels: cla-signed

#3730 Update change log week of 7/28
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3724 First Steps into making Gradle Catalogs
  app/build.gradle.kts
  automotive/build.gradle.kts
  build.gradle.kts
  common/build.gradle.kts
  gradle/libs.versions.toml
  wear/build.gradle.kts
Labels: cla-signed

#3697 Implement support for multiple Shortcut Tiles on Wear OS
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/WearPrefsRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/WearPrefsRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/util/JsonUtil.kt
  common/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenter.kt
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SelectShortcutsTileView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetShortcutsTileView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationPresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/OpenShortcutTileSettingsActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
Labels: cla-signed, Wear OS

#3732 Allow binary sensors and sensors to be added to driving favorites
  app/src/main/java/io/homeassistant/companion/android/settings/vehicle/ManageAndroidAutoViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/vehicle/views/AndroidAutoFavoritesView.kt
  app/src/main/java/io/homeassistant/companion/android/util/vehicle/DomainChecks.kt
  app/src/main/java/io/homeassistant/companion/android/util/vehicle/GridItems.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/DomainListScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Labels: cla-signed, Android Auto

#3733 Allow selecting unavailable entities for complications/tiles
  wear/src/main/java/io/homeassistant/companion/android/views/ChooseEntityView.kt
Labels: cla-signed, Wear OS

#3736 Invalidate Auto home on favorite state change
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Labels: cla-signed, Android Auto

#3740 Hide some sensors from unsupported devices
  app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LastAppSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/DNDSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/NextAlarmManager.kt
Labels: cla-signed
