Repository home-assistant/android, pull requests merged in 2023-08, with the labels that each got.

#3737 Initial work on migrating plugins to catalogs.
  app/build.gradle.kts
  automotive/build.gradle.kts
  build.gradle.kts
  common/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
  wear/build.gradle.kts
Labels: cla-signed

#3746 Ignore ruby files that were generated in CI.
  .gitignore
  fastlane/Fastfile
Labels: cla-signed

#3748 Update release notes action for new release model
  .github/actions/create-release-notes/action.yml
  .github/workflows/onPush.yml
  .github/workflows/pr.yml
Labels: cla-signed

#3749 Don't create release number/notes for PRs
  .github/workflows/pr.yml
Labels: cla-signed

#3750 Change SDK min back to 21 for main app
  gradle/libs.versions.toml
Labels: cla-signed

#3753 Fix persistent connection notification command
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed

#3754 Reset carInfo when our session is destroyed since data will be stale
  app/src/main/java/io/homeassistant/companion/android/vehicle/HaCarAppService.kt
Labels: cla-signed, Android Auto

#3757 Keep track of adding domains to remove loader when user has no actionable entities
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Labels: cla-signed, Android Auto

#3760 Update ExoPlayer usage
  app/build.gradle.kts
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/res/drawable/ic_baseline_fullscreen_24.xml
  app/src/main/res/drawable/ic_baseline_fullscreen_exit_24.xml
  app/src/main/res/drawable/ic_baseline_volume_off_24.xml
  app/src/main/res/drawable/ic_baseline_volume_up_24.xml
  app/src/main/res/layout/activity_webview.xml
  app/src/main/res/layout/exo_player_control_view.xml
  app/src/main/res/layout/exo_player_view.xml
  app/src/main/res/values/styles.xml
  automotive/build.gradle.kts
  common/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: cla-signed

#3758 Change log week of 8/4
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3764 Set car sensors state appropriately if sensor registers with unit of measurement
  app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Android Auto

#3765 Add support for alarm control panels in android auto
  app/src/main/java/io/homeassistant/companion/android/util/vehicle/DomainChecks.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Android Auto

#3768 Update strings for sentence-style casing
  common/src/main/res/values/strings.xml
Labels: cla-signed

#3767 Hide all entities when we dont have domains to show, show empty message just in case
  app/src/main/java/io/homeassistant/companion/android/util/vehicle/GridItems.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/DomainListScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Labels: cla-signed, Android Auto

#3769 Auto: reload entity registry, show loading when changing servers
  app/src/main/java/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
Labels: cla-signed, Android Auto

#3774 Add update sensors notification command to Wear OS
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/notifications/DeviceCommands.kt
  wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed, Wear OS

#3780 Update change log week of 8/11
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3784 Discard notifications when not registered to prevent crash
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  wear/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed

#3776 Replace deprecated menu functions with MenuProvider
  app/src/full/java/io/homeassistant/companion/android/settings/wear/SettingsWearActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/HelpMenuProvider.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
  app/src/main/java/io/homeassistant/companion/android/settings/controls/ManageControlsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/controls/views/ManageControlsView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/log/LogFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationChannelFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationHistoryFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/notification/NotificationMenuProvider.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorSettingsViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorUpdateFrequencyFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/url/ExternalUrlFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/vehicle/ManageAndroidAutoSettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/websocket/WebsocketSettingFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/widgets/ManageWidgetsSettingsFragment.kt
  app/src/main/res/menu/menu_activity_settings.xml
  app/src/main/res/menu/menu_fragment_log.xml
  app/src/main/res/menu/menu_fragment_notification.xml
  app/src/main/res/menu/menu_fragment_sensor.xml
  app/src/main/res/menu/menu_fragment_sensordetail.xml
  app/src/main/res/menu/menu_help.xml
Labels: cla-signed

#3782 Bump compile SDK to 34 (Android 14)
  gradle/libs.versions.toml
Labels: cla-signed

#3799 Catch errors when intent URI is not valid
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
Labels: cla-signed

#3803 Fix phone state sensor only considering 1 subscription's calls
  common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt
Labels: cla-signed

#3798 Add 'toggle' tap action to entity state widget
  app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
  app/src/main/java/io/homeassistant/companion/android/settings/qs/ManageTilesFragment.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
  app/src/main/res/layout/widget_static.xml
  app/src/main/res/layout/widget_static_configure.xml
  common/schemas/io.homeassistant.companion.android.database.AppDatabase/43.json
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
  common/src/main/java/io/homeassistant/companion/android/database/AppDatabase.kt
  common/src/main/java/io/homeassistant/companion/android/database/widget/StaticWidgetEntity.kt
  common/src/main/java/io/homeassistant/companion/android/database/widget/WidgetTapAction.kt
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/home/HomePresenterImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/TileActionReceiver.kt
Labels: cla-signed

#3804 Update Changelog for 2023.8.3
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3814 Update to Kotlin 1.9/Compose 1.5/Compose Wear 1.2/AGP 8.1.1
  build.gradle.kts
  common/build.gradle.kts
  gradle/libs.versions.toml
  wear/build.gradle.kts
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/DetailsPanelView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityListView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SelectShortcutsTileView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorManagerUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetShortcutsTileView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/TemplateTileSettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/TimeText.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/phoneinstall/PhoneInstallView.kt
  wear/src/main/java/io/homeassistant/companion/android/views/ChooseEntityView.kt
  wear/src/main/java/io/homeassistant/companion/android/views/ThemeLazyColumn.kt
Labels: cla-signed

#3813 Fix restoring custom fields in service button widget
  app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt
Labels: cla-signed

#3815 More dependency bumps
  gradle/libs.versions.toml
  wear/build.gradle.kts
  wear/src/main/java/io/homeassistant/companion/android/tiles/ConversationTile.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/LoggedOutTile.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/TemplateTile.kt
  wear/src/main/res/layout/view_loading.xml
Labels: cla-signed

#3816 Various changes to entity usage
  app/src/main/java/io/homeassistant/companion/android/controls/CameraControl.kt
  app/src/main/java/io/homeassistant/companion/android/controls/ClimateControl.kt
  app/src/main/java/io/homeassistant/companion/android/controls/CoverControl.kt
  app/src/main/java/io/homeassistant/companion/android/controls/DefaultSwitchControl.kt
  app/src/main/java/io/homeassistant/companion/android/controls/FanControl.kt
  app/src/main/java/io/homeassistant/companion/android/controls/HaControl.kt
  app/src/main/java/io/homeassistant/companion/android/controls/LightControl.kt
  app/src/main/java/io/homeassistant/companion/android/controls/LockControl.kt
  app/src/main/java/io/homeassistant/companion/android/controls/VacuumControl.kt
  app/src/main/java/io/homeassistant/companion/android/qs/TileExtensions.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
Labels: cla-signed

#3820 Thread updates: add border agent ID, multiserver improvements
  app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
  app/src/main/java/io/homeassistant/companion/android/thread/ThreadManager.kt
  app/src/minimal/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/IntegrationRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/entities/ThreadDatasetResponse.kt
Labels: cla-signed

#3819 Update change log week of 8/25
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#3826 Improve handling my link when not logged in
  app/src/main/java/io/homeassistant/companion/android/launch/my/MyActivity.kt
Labels: cla-signed

#3821 Use unavailable and unknown states consistently when dealing with sensors and entities
  app/src/full/java/io/homeassistant/companion/android/sensors/ActivitySensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/sensors/GeocodeSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/controls/CameraControl.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/LastAppSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/AndroidOsSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/AudioSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/DNDSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/LastRebootSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/NextAlarmManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/util/States.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/EntityUi.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
Labels: cla-signed

#3825 Fix last update sensor intent not retrieving value
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
Labels: cla-signed

#3828 Fix Thread border agent IDs encoded as hex
  app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
Labels: cla-signed

#3829 Prevent entity ID typos throwing errors
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed

#3827 Clean up some left over code after update to getIcon
  app/src/main/java/io/homeassistant/companion/android/util/vehicle/GridItems.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
  wear/src/main/java/io/homeassistant/companion/android/complications/EntityStateDataSourceService.kt
  wear/src/main/java/io/homeassistant/companion/android/complications/views/ComplicationConfigMainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/MainView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetFavoriteView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SetShortcutsTileView.kt
  wear/src/main/java/io/homeassistant/companion/android/tiles/ShortcutsTile.kt
  wear/src/main/java/io/homeassistant/companion/android/util/CommonFunctions.kt
  wear/src/main/java/io/homeassistant/companion/android/views/ChooseEntityView.kt
Labels: cla-signed

#3831 Shortcut path input improvements
  app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/views/ManageShortcutsView.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebView.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  common/src/main/java/io/homeassistant/companion/android/util/UrlUtil.kt
Labels: cla-signed
