Repository home-assistant/android, pull requests merged in 2024-10, with the labels that each got.

#4687 Fix data URI download notification on Android 14+
  app/src/main/java/io/homeassistant/companion/android/util/DataUriDownloadManager.kt
Labels: cla-signed, Hacktoberfest

#4696 Breaking change: Improve sensor mobile_data
  common/src/main/java/io/homeassistant/companion/android/common/sensors/MobileDataManager.kt
Labels: cla-signed, Hacktoberfest

#4697 Wide screen onboarding: center text, limit width
  app/src/full/java/io/homeassistant/companion/android/matter/views/MatterCommissioningView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/OnboardingViews.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/manual/ManualSetupView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/notifications/NotificationPermissionView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/welcome/WelcomeView.kt
  app/src/main/java/io/homeassistant/companion/android/util/compose/Theme.kt
Labels: cla-signed, Hacktoberfest

#4695 Update change log week of 10/4
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed, Hacktoberfest

#4663 Revert "Temporarily disable health connect to satisfy play console"
  app/src/full/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed

#4702 Skip weight records update if empty
  app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
Labels: cla-signed, Hacktoberfest

#4698 Add energy device class to (kilo)calories sensors
  app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/HealthServicesSensorManager.kt
Labels: cla-signed, Hacktoberfest

#4634 Add 2 different display sensors around various screen states
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/DisplaySensorManager.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#4652 Catch automotive exception and allow sensors to be enabled via server side
  app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/vehicle/BaseVehicleScreen.kt
Labels: cla-signed, Android Auto

#4706 Fix 's in sensor descriptions
  common/src/main/res/values/strings.xml
Labels: cla-signed, Hacktoberfest

#4710 Update strings/sensor descriptions for consistency and clarity
  common/src/main/res/values/strings.xml
Labels: cla-signed, Hacktoberfest

#4714 Fix inconsistent MAC address capitalization
  common/src/main/res/values/strings.xml
Labels: cla-signed, Hacktoberfest

#4715 Migrate setup-java action to use Temurin (two more)
  .github/workflows/pr.yml
Labels: cla-signed, Hacktoberfest

#4716 Don't include Health Connect library in minimal
  app/build.gradle.kts
  app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
  app/src/minimal/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
  automotive/build.gradle.kts
Labels: cla-signed, Hacktoberfest

#4719 Improve Health Connect code quality
  app/src/full/AndroidManifest.xml
  app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
  app/src/full/java/io/homeassistant/companion/android/settings/sensor/HealthConnectPermissionActivity.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsActivity.kt
Labels: cla-signed, Hacktoberfest

#4718 Update change log week of 10/11
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed, Hacktoberfest

#4724 Disable Health Connect due to policy rejection
  app/src/full/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed, Hacktoberfest

#4721 Fix leading zero handling in toJsonType method
  app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetDynamicFieldAdapter.kt
Labels: cla-signed, Hacktoberfest

#4722 Add car speed sensor
  app/src/full/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
  automotive/src/main/AndroidManifest.xml
  common/src/main/res/values/strings.xml
Labels: cla-signed, Hacktoberfest, Android Auto

#4732 Add arrow to bottom sheet list items to indicate tappable
  app/src/main/java/io/homeassistant/companion/android/improv/ui/ImprovSheetView.kt
  app/src/main/java/io/homeassistant/companion/android/onboarding/discovery/DiscoveryView.kt
  app/src/main/java/io/homeassistant/companion/android/settings/server/ServerChooserView.kt
  app/src/main/res/drawable/navigate_next.xml
  app/src/main/res/layout/instance_item.xml
Labels: cla-signed, Hacktoberfest

#4734 Sensor descriptions and UI strings writing feedback
  common/src/main/res/values/strings.xml
Labels: cla-signed, Hacktoberfest

#4733 Add a car range remaining sensor
  app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Hacktoberfest

#4740 Prevent crash due to any Improv scanning failure
  app/src/main/java/io/homeassistant/companion/android/improv/ImprovRepositoryImpl.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed, Hacktoberfest

#4741 Avoid (s) in strings if possible
  common/src/main/java/io/homeassistant/companion/android/common/util/DisabledLocationHandler.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed, Hacktoberfest

#4745 Update change log week of 10/18
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed, Hacktoberfest

#4746 Correct sensor identification for car speed sensor
  app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
Labels: cla-signed, Hacktoberfest

#4731 Enable Health Connect again to retry for approval
  app/src/full/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed, Hacktoberfest

#4751 Hide widgets from automotive build and prevent intent registration too
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
Labels: cla-signed, Hacktoberfest

#4750 Add package name to health connect sensors, additional sensor tweaks
  app/src/full/java/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
Labels: cla-signed, Hacktoberfest

#4757 Allow fan domain to be selected for android auto favorites list
  app/src/main/java/io/homeassistant/companion/android/util/vehicle/DomainChecks.kt
Labels: cla-signed, Hacktoberfest

#4773 Fix pipeline badge in the header of README.md
  README.md
Labels: cla-signed, Hacktoberfest

#4774 Improve wording, grammar, and punctuation in README.md
  README.md
Labels: cla-signed, Hacktoberfest

#4765 Don't reset work profile state on app restart and add "intent only" update type
  app/src/main/java/io/homeassistant/companion/android/sensors/DevicePolicyManager.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/NotificationSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorManager.kt
  common/src/main/res/values/strings.xml
  wear/src/main/java/io/homeassistant/companion/android/sensors/WetModeSensorManager.kt
Labels: cla-signed, Hacktoberfest

#4763 Support behavior: textInput key on notification action for reply actions
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/NotificationAction.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/NotificationActionReceiver.kt
  app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt
Labels: cla-signed, Hacktoberfest

#4766 Add notification command for turning the flashlight on/off
  app/src/main/java/io/homeassistant/companion/android/BaseActivity.kt
  app/src/main/java/io/homeassistant/companion/android/notifications/MessagingManager.kt
  app/src/main/java/io/homeassistant/companion/android/util/FlashlightHelper.kt
  app/src/main/java/io/homeassistant/companion/android/util/PermissionRequestMediator.kt
Labels: cla-signed, Hacktoberfest
