Repository home-assistant/android, pull requests merged in 2024-09, with the labels that each got.

#4609 Add aab artifact to push action
  .github/workflows/onPush.yml
Labels: cla-signed

#4610 Temporarily disable health connect to satisfy play console
  app/src/full/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt
Labels: cla-signed

#4551 Handle notification permission on Wear
  wear/src/main/java/io/homeassistant/companion/android/home/HomeActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/home/MainViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/HomeView.kt
  wear/src/main/java/io/homeassistant/companion/android/home/views/SettingsView.kt
  wear/src/main/java/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/phone/PhoneSettingsListener.kt
Labels: cla-signed

#4552 Breaking Change: Update heart rate sensor for Wear OS 4+ target
  wear/src/main/AndroidManifest.xml
  wear/src/main/java/io/homeassistant/companion/android/home/views/SensorUi.kt
  wear/src/main/java/io/homeassistant/companion/android/sensors/HeartRateSensorManager.kt
Labels: cla-signed

#4559 Add (NOT_)EXPORTED to registerReceiver for Android 14 target
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
  app/src/main/java/io/homeassistant/companion/android/sensors/QuestSensorManager.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/BaseWidgetProvider.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidget.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/BatterySensorManager.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt
  wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
Labels: cla-signed

#4561 Add foreground service types for Android 14 target
  app/src/full/AndroidManifest.xml
  app/src/full/java/io/homeassistant/companion/android/location/HighAccuracyLocationService.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/io/homeassistant/companion/android/util/ForegroundServiceLauncher.kt
  app/src/main/java/io/homeassistant/companion/android/websocket/WebsocketManager.kt
  automotive/src/full/AndroidManifest.xml
  automotive/src/main/AndroidManifest.xml
  common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorWorkerBase.kt
  wear/src/main/AndroidManifest.xml
Labels: cla-signed

#4611 Bump target SDK to Android 14 (app) / 13 (Wear)
  gradle/libs.versions.toml
Labels: cla-signed

#4612 Update Change log week of 9/6
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#4596 Open onboarding when Assist is launched when not registered
  app/src/main/java/io/homeassistant/companion/android/assist/AssistActivity.kt
  common/src/main/java/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
Labels: cla-signed, Assist

#4579 Load sensor setting dialog entries async
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/SensorDetailViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
Labels: cla-signed

#4618 add transparent background to media widget
  app/src/main/java/io/homeassistant/companion/android/widgets/button/ButtonWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetUtils.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/entity/EntityWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidget.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/mediaplayer/MediaPlayerControlsWidgetConfigureActivity.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
  app/src/main/res/layout/widget_media_controls_configure.xml
Labels: cla-signed

#4578 Add Page zoom setting
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/java/io/homeassistant/companion/android/settings/SettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/main/res/drawable/ic_zoom_in.xml
  app/src/main/res/xml/preferences.xml
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/prefs/PrefsRepositoryImpl.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#4555 Don't build minimal flavors for Play Publish workflow task
  .github/workflows/onPush.yml
Labels: cla-signed

#4546 Allow measured power to be updated via notification command
  common/src/main/java/io/homeassistant/companion/android/common/notifications/DeviceCommands.kt
  common/src/main/java/io/homeassistant/companion/android/common/sensors/BluetoothSensorManager.kt
Labels: cla-signed

#4575 Add signal strength and data network type sensors
  app/src/main/AndroidManifest.xml
  common/src/main/AndroidManifest.xml
  common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt
  common/src/main/res/values/strings.xml
  wear/src/main/AndroidManifest.xml
Labels: cla-signed

#4616 Prevent socket response continuation being called multiple times (#3338)
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRequest.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Labels: cla-signed

#4631 Add unit of measurement and device class for signal strength sensors
  common/src/main/java/io/homeassistant/companion/android/common/sensors/PhoneStateSensorManager.kt
Labels: cla-signed

#4635 Bump compile SDK to 35
  gradle/libs.versions.toml
Labels: cla-signed

#4636 Update change log week of 9/13
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#4647 Updates .gitignore to not include .kotlin/ changes into git
  .gitignore
Labels: cla-signed

#4659 Update change log week of 9/20
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#4649 Widget placeholder UI Improvements
  app/src/main/res/layout/widget_button.xml
  app/src/main/res/layout/widget_camera.xml
  app/src/main/res/layout/widget_media_controls.xml
  app/src/main/res/xml/entity_widget_info.xml
Labels: cla-signed

#4662 Use correct location batching call
  app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt
Labels: cla-signed

#4666 Fix update type identification on some network sensors
  common/src/main/java/io/homeassistant/companion/android/common/sensors/NetworkSensorManager.kt
Labels: cla-signed

#4670 Make WifiHelper available in getServer fallback
  common/src/main/java/io/homeassistant/companion/android/common/data/servers/ServerManagerImpl.kt
Labels: cla-signed

#4671 Correct null check to avoid errors in pip
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
Labels: cla-signed

#4674 Allow only spaces SSID when configuring home network wifi (#3354)
  app/src/main/java/io/homeassistant/companion/android/settings/ssid/SsidViewModel.kt
Labels: cla-signed, cla-error

#4678 Add OHF logo to README
  README.md
Labels: cla-signed

#4661 Use receiver exported for all sensor receiver intents
  app/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
  app/src/main/java/io/homeassistant/companion/android/nfc/NfcSetupActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/HomeAssistantApplication.kt
Labels: cla-signed
