Repository home-assistant/android, pull requests merged in 2024-01, with the labels that each got.

#4069 Send IP address of Matter device for on network commissioning
  app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningService.kt
  app/src/full/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
  app/src/main/java/io/homeassistant/companion/android/matter/MatterManager.kt
  app/src/minimal/java/io/homeassistant/companion/android/matter/MatterManagerImpl.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/WebSocketRepository.kt
  common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt
Labels: cla-signed

#4119 Add padding to refresh interval to avoid text getting cut off
  wear/src/main/java/io/homeassistant/companion/android/home/views/RefreshIntervalPickerView.kt
Labels: cla-signed, Wear OS

#4117 Update change log week of 1/5
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#4120 Use horizontal padding on refresh interval per review comment
  wear/src/main/java/io/homeassistant/companion/android/home/views/RefreshIntervalPickerView.kt
Labels: cla-signed

#4128 Support for Thread "import credentials" from frontend
  app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningViewModel.kt
  app/src/full/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
  app/src/main/java/io/homeassistant/companion/android/matter/MatterFrontendCommissioningStatus.kt
  app/src/main/java/io/homeassistant/companion/android/settings/developer/DeveloperSettingsPresenterImpl.kt
  app/src/main/java/io/homeassistant/companion/android/thread/ThreadManager.kt
  app/src/main/java/io/homeassistant/companion/android/webview/MatterThreadStep.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenter.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
  app/src/minimal/java/io/homeassistant/companion/android/thread/ThreadManagerImpl.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#4132 Bump some project dependencies
  gradle/libs.versions.toml
Labels: cla-signed

#4133 Update change log week of 1/12
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#4122 Integrate car sensors with automotive, and added permissions
  app/src/main/java/io/homeassistant/companion/android/sensors/CarSensorManager.kt
  automotive/src/main/AndroidManifest.xml
Labels: cla-signed

#4144 Replace 'Refresh interval' title with icon
  wear/src/main/java/io/homeassistant/companion/android/home/views/RefreshIntervalPickerView.kt
Labels: cla-signed, Wear OS

#4150 Remove Thread credential sync from start of Matter commissioning flow
  app/src/full/java/io/homeassistant/companion/android/matter/MatterCommissioningViewModel.kt
  app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
Labels: cla-signed

#4155 Bump play services location dependency
  gradle/libs.versions.toml
Labels: cla-signed

#4159 Support image entity in camera widget (now renamed picture widget)
  app/src/main/java/io/homeassistant/companion/android/settings/widgets/views/ManageWidgetsView.kt
  app/src/main/java/io/homeassistant/companion/android/widgets/camera/CameraWidgetConfigureActivity.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#4165 Androidx dependency updates late Jan 2024
  app/src/main/java/io/homeassistant/companion/android/nfc/views/NfcNavigationView.kt
  gradle/libs.versions.toml
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
Labels: cla-signed

#4163 Update change log week of 1/26
  app/src/main/res/xml/changelog_master.xml
Labels: cla-signed

#4174 Wear Assist: show login when logged out, scroll first item into view
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationActivity.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/ConversationViewModel.kt
  wear/src/main/java/io/homeassistant/companion/android/conversation/views/ConversationView.kt
Labels: cla-signed, Wear OS, Assist
