Repository home-assistant/android, pull requests merged in 2025-09, with the labels that each got.

#5714 Bump Wear versions
  gradle/libs.versions.toml
  wear/gradle.lockfile
Labels: cla-signed

#5722 Remove runBlocking from ServerManager.activeServerId
  app/lint-baseline.xml
  app/src/main/kotlin/io/homeassistant/companion/android/util/vehicle/GridItems.kt
  app/src/main/kotlin/io/homeassistant/companion/android/vehicle/DomainListScreen.kt
  app/src/main/kotlin/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  app/src/main/kotlin/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
  app/src/main/kotlin/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
  app/src/test/kotlin/io/homeassistant/companion/android/widgets/BaseGlanceEntityWidgetReceiverTest.kt
  app/src/test/kotlin/io/homeassistant/companion/android/widgets/todo/TodoWidgetStateUpdaterTest.kt
  app/src/test/kotlin/io/homeassistant/companion/android/widgets/todo/TodoWidgetToggleActionsTest.kt
  automotive/lint-baseline.xml
  common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/impl/IntegrationRepositoryImpl.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/data/servers/ServerManager.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/data/servers/ServerManagerImpl.kt
  common/src/test/kotlin/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketCoreImplTest.kt
  wear/src/main/kotlin/io/homeassistant/companion/android/home/HomePresenter.kt
  wear/src/main/kotlin/io/homeassistant/companion/android/home/HomePresenterImpl.kt
Labels: cla-signed

#5685 Set end time for Health Connect aggregation request to end of day
  app/src/full/kotlin/io/homeassistant/companion/android/sensors/HealthConnectSensorManager.kt
Labels: cla-signed

#5698 Remove all runBlocking from WebViewPresenter
  app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewPresenter.kt
  app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt
Labels: cla-signed

#5734 Introduce HALoading and HAProgress
  app/src/debug/kotlin/io/homeassistant/companion/android/developer/catalog/HAComposeCatalogScreen.kt
  app/src/screenshotTestFullDebug/reference/io/homeassistant/companion/android/developer/HAComposeCatalogScreenshotTest/HAComposeCatalog default screen_Dark_70a0f41f_0.png
  app/src/screenshotTestFullDebug/reference/io/homeassistant/companion/android/developer/HAComposeCatalogScreenshotTest/HAComposeCatalog default screen_Light_d3da7775_0.png
  common/src/main/kotlin/io/homeassistant/companion/android/common/compose/composable/HAProgress.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/compose/theme/HAColors.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/compose/theme/HASize.kt
  common/src/screenshotTest/kotlin/io/homeassistant/companion/android/compose/composable/HAProgressScreenshotTest.kt
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAProgressScreenshotTest/HALoading_Dark_d19fbf1f_0.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAProgressScreenshotTest/HALoading_Light_b29dc7a7_0.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAProgressScreenshotTest/HAProgress for fixed value_Dark_d19fbf1f_79257149_0.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAProgressScreenshotTest/HAProgress for fixed value_Dark_d19fbf1f_79257149_1.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAProgressScreenshotTest/HAProgress for fixed value_Dark_d19fbf1f_79257149_2.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAProgressScreenshotTest/HAProgress for fixed value_Dark_d19fbf1f_79257149_3.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAProgressScreenshotTest/HAProgress for fixed value_Light_b29dc7a7_79257149_0.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAProgressScreenshotTest/HAProgress for fixed value_Light_b29dc7a7_79257149_1.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAProgressScreenshotTest/HAProgress for fixed value_Light_b29dc7a7_79257149_2.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAProgressScreenshotTest/HAProgress for fixed value_Light_b29dc7a7_79257149_3.png
Labels: cla-signed, UX/UI Review

#5746 Fix race when opening template widget screen for rendering template
  app/src/main/kotlin/io/homeassistant/companion/android/widgets/template/TemplateWidgetConfigureActivity.kt
Labels: cla-signed

#5749 Fix device controls settings not selecting a server by default
  app/src/main/kotlin/io/homeassistant/companion/android/settings/controls/views/ManageControlsView.kt
Labels: cla-signed

#5787 Pin SHA for all Github Actions
  .github/actions/create-release-notes/action.yml
  .github/actions/setup-build-env/action.yml
  .github/actions/upload-sarif-results/action.yml
  .github/workflows/monthly.yml
  .github/workflows/onPush.yml
  .github/workflows/pr.yml
  .github/workflows/prepareNextRelease.yml
  .github/workflows/release.yml
  .github/workflows/updateScreenshot.yml
  .github/workflows/weekly.yml
Labels: cla-signed

#5797 Add appVersion and downloadFileSupported to external bus config response
  app/src/main/kotlin/io/homeassistant/companion/android/webview/WebViewActivity.kt
  app/src/main/kotlin/io/homeassistant/companion/android/webview/externalbus/ExternalBusMessage.kt
Labels: cla-signed

#5170 Add WearDns for handling DNS resolution on Wear devices
  app/gradle.lockfile
  app/src/full/AndroidManifest.xml
  app/src/full/kotlin/io/homeassistant/companion/android/data/wear/WearDnsRequestListener.kt
  app/src/full/res/values/wear.xml
  app/src/main/kotlin/io/homeassistant/companion/android/ApplicationModule.kt
  app/src/test/kotlin/io/homeassistant/companion/android/data/wear/ShadowDnsSystem.kt
  app/src/test/kotlin/io/homeassistant/companion/android/data/wear/WearDnsRequestListenerTest.kt
  automotive/gradle.lockfile
  build-logic/convention/src/main/kotlin/AndroidApplicationDependenciesConventionPlugin.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/data/HomeAssistantApis.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/data/keychain/KeyStoreRepositoryImpl.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/util/WearDataMessages.kt
  common/src/main/kotlin/io/homeassistant/companion/android/di/DataModule.kt
  gradle/libs.versions.toml
  wear/build.gradle.kts
  wear/gradle.lockfile
  wear/src/main/kotlin/io/homeassistant/companion/android/ApplicationModule.kt
  wear/src/main/kotlin/io/homeassistant/companion/android/data/WearDataModule.kt
  wear/src/main/kotlin/io/homeassistant/companion/android/data/WearDns.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/data/WearDnsTest.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/shadows/FakeCapabilityClient.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/shadows/FakeCapabilityInfo.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/shadows/FakeClock.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/shadows/FakeMessageClient.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/shadows/FakeNode.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/shadows/FakeTask.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/shadows/ShadowDnsSystem.kt
Labels: cla-signed, Wear OS

#5804 Improve unit tests
  .idea/runConfigurations/Unit_tests.xml
  app/src/full/kotlin/io/homeassistant/companion/android/data/wear/WearDnsRequestListener.kt
  app/src/test/kotlin/io/homeassistant/companion/android/data/wear/ShadowDnsSystem.kt
  app/src/test/kotlin/io/homeassistant/companion/android/data/wear/WearDnsRequestListenerTest.kt
  app/src/test/kotlin/io/homeassistant/companion/android/util/ChangeLogTest.kt
  gradle/libs.versions.toml
  wear/build.gradle.kts
  wear/gradle.lockfile
  wear/src/main/kotlin/io/homeassistant/companion/android/data/WearDns.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/data/WearDnsTest.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/fakes/FakeCapabilityClient.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/fakes/FakeCapabilityInfo.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/fakes/FakeClock.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/fakes/FakeDns.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/fakes/FakeMessageClient.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/fakes/FakeNode.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/fakes/FakeTask.kt
  wear/src/test/kotlin/io/homeassistant/companion/android/shadows/ShadowDnsSystem.kt
Labels: cla-signed

#5807 Fix `UseKtx` lint warnings in `app` module
  app/lint-baseline.xml
  app/src/full/kotlin/io/homeassistant/companion/android/settings/sensor/HealthConnectPermissionActivity.kt
  app/src/full/kotlin/io/homeassistant/companion/android/settings/wear/SettingsWearActivity.kt
  app/src/full/kotlin/io/homeassistant/companion/android/settings/wear/views/SettingsWearHomeView.kt
  app/src/main/kotlin/io/homeassistant/companion/android/barcode/BarcodeScannerActivity.kt
  app/src/main/kotlin/io/homeassistant/companion/android/nfc/views/NfcNavigationView.kt
  app/src/main/kotlin/io/homeassistant/companion/android/onboarding/integration/MobileAppIntegrationFragment.kt
  app/src/main/kotlin/io/homeassistant/companion/android/settings/SettingsFragment.kt
  app/src/main/kotlin/io/homeassistant/companion/android/settings/developer/location/views/LocationTrackingView.kt
  app/src/main/kotlin/io/homeassistant/companion/android/settings/sensor/views/SensorDetailView.kt
  automotive/lint-baseline.xml
Labels: cla-signed

#5819 Fix `UseKtx` lint warnings in `wear` module
  app/lint-baseline.xml
  automotive/lint-baseline.xml
  wear/lint-baseline.xml
  wear/src/main/kotlin/io/homeassistant/companion/android/onboarding/OnboardingActivity.kt
  wear/src/main/kotlin/io/homeassistant/companion/android/onboarding/OnboardingPresenterImpl.kt
  wear/src/main/kotlin/io/homeassistant/companion/android/onboarding/manual/ManualSetupPresenterImpl.kt
  wear/src/main/kotlin/io/homeassistant/companion/android/onboarding/phoneinstall/PhoneInstallActivity.kt
  wear/src/main/kotlin/io/homeassistant/companion/android/tiles/CameraTile.kt
  wear/src/main/kotlin/io/homeassistant/companion/android/util/LoadingView.kt
Labels: cla-signed

#5815 Improve ux server discovery and connection screen
  onboarding/src/main/kotlin/io/homeassistant/companion/android/compose/HAPreviews.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/compose/composable/HAWebView.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/loading/LoadingScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/connection/ConnectionScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/connection/ConnectionViewModel.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/serverdiscovery/ServerDiscoveryScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/serverdiscovery/ServerDiscoveryViewModel.kt
  onboarding/src/screenshotTest/kotlin/io/homeassistant/companion/android/onboarding/connection/ConnectionScreenshotTest.kt
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/connection/ConnectionScreenshotTest/ConnectionScreen error_small_phone_66e7bbf2_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/connection/ConnectionScreenshotTest/ConnectionScreen error_tablet_2f22c4ea_0.png
  onboarding/src/test/kotlin/io/homeassistant/companion/android/onboarding/OnboardingNavigationTest.kt
  onboarding/src/test/kotlin/io/homeassistant/companion/android/onboarding/connection/ConnectionScreenTest.kt
  onboarding/src/test/kotlin/io/homeassistant/companion/android/onboarding/connection/ConnectionViewModelTest.kt
  onboarding/src/test/kotlin/io/homeassistant/companion/android/onboarding/serverdiscovery/ServerDiscoveryScreenTest.kt
Labels: cla-signed

#5827 Fix `UseKtx` and `TypographyDashes` lint warnings in `common` module
  common/lint-baseline.xml
  common/src/main/kotlin/io/homeassistant/companion/android/common/notifications/NotificationFunctions.kt
  common/src/main/res/values/strings.xml
Labels: cla-signed

#5766 Add onboarding local first screen
  onboarding/lint-baseline.xml
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/OnboardingNavigation.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/localfirst/navigation/LocalFirstNavigation.kt
  onboarding/src/main/res/drawable-night/ic_no_remote.xml
  onboarding/src/main/res/drawable/ic_no_remote.xml
  onboarding/src/main/res/values/strings.xml
  onboarding/src/screenshotTest/kotlin/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest.kt
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest/LocalFirstContent empty_Dark_d19fbf1f_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest/LocalFirstContent empty_Light_b29dc7a7_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest/LocalFirstContent empty_foldable_c908f502_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest/LocalFirstContent empty_phone_e05166be_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest/LocalFirstContent empty_phone_landscape_9e00b29d_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest/LocalFirstContent empty_small_phone_66e7bbf2_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest/LocalFirstContent empty_small_phone_d384a2f8_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest/LocalFirstContent empty_tablet_254c6bb7_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest/LocalFirstContent empty_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest/LocalFirstContent empty_tablet_landscape_62cae397_0.png
  onboarding/src/test/kotlin/io/homeassistant/companion/android/onboarding/OnboardingNavigationTest.kt
  onboarding/src/test/kotlin/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenTest.kt
Labels: cla-signed, UX/UI Review

#5844 Set maxlines to 1 in manual server and name your device screens
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/manualserver/ManualServerScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/nameyourdevice/NameYourDeviceScreen.kt
Labels: cla-signed

#5843 Add github tasks
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.yml
  .github/workflows/restrict-task-creation.yml
Labels: cla-signed
