Repository home-assistant/android, pull requests merged in 2025-10, with the labels that each got.

#5853 Update (deprecated) vehicle template header builder
  app/src/main/kotlin/io/homeassistant/companion/android/util/vehicle/TemplateComponents.kt
  app/src/main/kotlin/io/homeassistant/companion/android/vehicle/ChangeServerScreen.kt
  app/src/main/kotlin/io/homeassistant/companion/android/vehicle/DomainListScreen.kt
  app/src/main/kotlin/io/homeassistant/companion/android/vehicle/EntityGridVehicleScreen.kt
  app/src/main/kotlin/io/homeassistant/companion/android/vehicle/LoginScreen.kt
  app/src/main/kotlin/io/homeassistant/companion/android/vehicle/MainVehicleScreen.kt
  app/src/main/kotlin/io/homeassistant/companion/android/vehicle/MapVehicleScreen.kt
  automotive/lint-baseline.xml
Labels: cla-signed

#5850 Add HASwitch based on material3 Switch
  app/src/debug/kotlin/io/homeassistant/companion/android/developer/catalog/HAComposeCatalogScreen.kt
  app/src/screenshotTestFullDebug/reference/io/homeassistant/companion/android/developer/HAComposeCatalogScreenshotTest/HAComposeCatalog default screen_Dark_30e15b6f_0.png
  app/src/screenshotTestFullDebug/reference/io/homeassistant/companion/android/developer/HAComposeCatalogScreenshotTest/HAComposeCatalog default screen_Light_f28a9270_0.png
  common/src/main/kotlin/io/homeassistant/companion/android/common/compose/composable/HASwitch.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/compose/theme/HAColors.kt
  common/src/screenshotTest/kotlin/io/homeassistant/companion/android/compose/composable/HASwitchScreenshotTest.kt
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HASwitchScreenshotTest/HASwitch_Dark_d19fbf1f_0.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HASwitchScreenshotTest/HASwitch_Light_b29dc7a7_0.png
Labels: cla-signed, UX/UI Review

#5852 Adjust ha space naming
  app/src/debug/kotlin/io/homeassistant/companion/android/developer/catalog/HAComposeCatalogScreen.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/compose/composable/HAButtons.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/compose/composable/HARadioGroup.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/compose/theme/HASize.kt
  common/src/screenshotTest/kotlin/io/homeassistant/companion/android/compose/composable/HATextFieldScreenshotTest.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/locationforsecureconnection/LocationForSecureConnectionScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/locationsharing/LocationSharingScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/manualserver/ManualServerScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/nameyourdevice/NameYourDeviceScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/serverdiscovery/ServerDiscoveryScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/welcome/WelcomeScreen.kt
Labels: cla-signed

#5848 Add onboarding wear mTLS screen
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/OnboardingNavigation.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/nameyourweardevice/navigation/NameYourWearDeviceNavigation.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/wearmtls/WearMTLSScreen.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/wearmtls/WearMTLSViewModel.kt
  onboarding/src/main/kotlin/io/homeassistant/companion/android/onboarding/wearmtls/navigation/WearMTLSNavigation.kt
  onboarding/src/main/res/values/strings.xml
  onboarding/src/screenshotTest/kotlin/io/homeassistant/companion/android/onboarding/wearmtls/WearMTLSScreenshotTest.kt
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/wearmtls/WearMTLSScreenshotTest/WearMTLSScreen file selected_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/wearmtls/WearMTLSScreenshotTest/WearMTLSScreen no file selected_tablet_2f22c4ea_0.png
  onboarding/src/test/kotlin/io/homeassistant/companion/android/onboarding/WearOnboardingNavigationTest.kt
  onboarding/src/test/kotlin/io/homeassistant/companion/android/onboarding/wearmtls/WearMTLSScreenTest.kt
  onboarding/src/test/kotlin/io/homeassistant/companion/android/onboarding/wearmtls/WearMTLSViewModelTest.kt
Labels: cla-signed, UX/UI Review

#5861 Build release APK on PR
  .github/workflows/pr.yml
Labels: cla-signed, Hacktoberfest

#5890 Add missing content write permission for update screenshot workflow
  .github/workflows/updateScreenshot.yml
Labels: cla-signed, Hacktoberfest

#5892 Change default button size to MEDIUM
  app/src/screenshotTestFullDebug/reference/io/homeassistant/companion/android/developer/HAComposeCatalogScreenshotTest/HAComposeCatalog default screen_Dark_30e15b6f_0.png
  app/src/screenshotTestFullDebug/reference/io/homeassistant/companion/android/developer/HAComposeCatalogScreenshotTest/HAComposeCatalog default screen_Light_f28a9270_0.png
  common/src/main/kotlin/io/homeassistant/companion/android/common/compose/composable/HAButtons.kt
  common/src/main/kotlin/io/homeassistant/companion/android/common/compose/theme/HATextStyle.kt
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAAccentButton_Dark_d19fbf1f_d135a868_0.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAAccentButton_Dark_d19fbf1f_d135a868_1.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAAccentButton_Dark_d19fbf1f_d135a868_2.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAAccentButton_Dark_d19fbf1f_d135a868_3.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAAccentButton_Dark_d19fbf1f_d135a868_4.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAAccentButton_Light_b29dc7a7_d135a868_0.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAAccentButton_Light_b29dc7a7_d135a868_1.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAAccentButton_Light_b29dc7a7_d135a868_2.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAAccentButton_Light_b29dc7a7_d135a868_3.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAAccentButton_Light_b29dc7a7_d135a868_4.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAFilledButton_Dark_d19fbf1f_d135a868_0.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAFilledButton_Dark_d19fbf1f_d135a868_1.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAFilledButton_Dark_d19fbf1f_d135a868_2.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAFilledButton_Dark_d19fbf1f_d135a868_3.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAFilledButton_Dark_d19fbf1f_d135a868_4.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAFilledButton_Light_b29dc7a7_d135a868_0.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAFilledButton_Light_b29dc7a7_d135a868_1.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAFilledButton_Light_b29dc7a7_d135a868_2.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAFilledButton_Light_b29dc7a7_d135a868_3.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAFilledButton_Light_b29dc7a7_d135a868_4.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAPlainButton_Dark_d19fbf1f_d135a868_0.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAPlainButton_Dark_d19fbf1f_d135a868_1.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAPlainButton_Dark_d19fbf1f_d135a868_2.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAPlainButton_Dark_d19fbf1f_d135a868_3.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAPlainButton_Dark_d19fbf1f_d135a868_4.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAPlainButton_Light_b29dc7a7_d135a868_0.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAPlainButton_Light_b29dc7a7_d135a868_1.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAPlainButton_Light_b29dc7a7_d135a868_2.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAPlainButton_Light_b29dc7a7_d135a868_3.png
  common/src/screenshotTestDebug/reference/io/homeassistant/companion/android/compose/composable/HAButtonScreenshotTest/HAPlainButton_Light_b29dc7a7_d135a868_4.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/localfirst/LocalFirstScreenshotTest/LocalFirstContent empty_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/locationforsecureconnection/LocationForSecureConnectionScreenshotTest/LocationForSecureConnection empty_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/locationsharing/LocationSharingScreenshotTest/LocationSharing empty_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/manualserver/ManualServerScreenshotTest/ManualServerScreen empty_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/manualserver/ManualServerScreenshotTest/ManualServerScreen with valid url_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/manualserver/ManualServerScreenshotTest/ManualServerScreen with wrong url_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/nameyourdevice/NameYourDeviceScreenshotTest/NameYourDevice empty_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/nameyourdevice/NameYourDeviceScreenshotTest/NameYourDevice with a name_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/serverdiscovery/ServerDiscoveryScreenshotTest/ServerDiscoveryScreen no server found_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/serverdiscovery/ServerDiscoveryScreenshotTest/ServerDiscoveryScreen scanning_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/serverdiscovery/ServerDiscoveryScreenshotTest/ServerDiscoveryScreen with multiple servers found_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/serverdiscovery/ServerDiscoveryScreenshotTest/ServerDiscoveryScreen with one server found_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/wearmtls/WearMTLSScreenshotTest/WearMTLSScreen file selected_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/wearmtls/WearMTLSScreenshotTest/WearMTLSScreen no file selected_tablet_2f22c4ea_0.png
  onboarding/src/screenshotTestDebug/reference/io/homeassistant/companion/android/onboarding/welcome/WelcomeScreenshotTest/WelcomeScreen_tablet_2f22c4ea_0.png
Labels: cla-signed, Hacktoberfest, UX/UI Review
